// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// The skeleton owns fragment order; all scripts retain one inline scope
// so a file opened offline needs neither imports nor a module loader.
const root = import.meta.dir;
const skeleton = readFileSync(join(root, "src/skeleton.html"), "utf8");
const page = skeleton.replace(/^<!-- inline:([a-z]+\.(?:css|js)) -->\n/gm,
  (_, file) => readFileSync(join(root, "src", file), "utf8"));
const banner = "<!-- Generated by `bun crates/city/skills/playback/assemble.js`; edit src/ and regenerate. -->\n";
const generated = Buffer.from(page.replace("<!doctype html>\n", "<!doctype html>\n" + banner));
const output = join(root, "template.html");

if (process.argv.length === 2) {
  writeFileSync(output, generated);
  console.log("playback template regenerated");
} else if (process.argv.length === 3 && process.argv[2] === "--check") {
  if (!generated.equals(readFileSync(output))) {
    console.error("playback template is stale; run bun crates/city/skills/playback/assemble.js");
    process.exit(1);
  }
  console.log("playback template matches its sources byte for byte");
} else {
  console.error("usage: bun crates/city/skills/playback/assemble.js [--check]");
  process.exit(1);
}
