// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
//
// Generated by `cargo xtask wire-ts` from `crates/channels` (channels-SPEC.md
// section 8-16). Do not edit: change the Rust wire types and regenerate.

import { Schema } from "effect";

/** The wire version both ends compare on connect. */
export const WIRE_V = 20 as const;
/** The schema hash the server checks: `channels::schema_hash()`. */
export const WIRE_HASH = "a249f589f1b45771bb1f08e2b36e32e26be3cbfc1e1011fe34f88a614001c0b1" as const;

/**
 * Canonical relative path; invariants enforced at the sole constructor.
 */
export const Address = Schema.String.pipe(Schema.brand("Address"));
export type Address = typeof Address.Type;

/**
 * Non-empty item identity; uuid v7 minting is the effect layer's.
 */
export const ApprovalId = Schema.String.pipe(Schema.brand("ApprovalId"));
export type ApprovalId = typeof ApprovalId.Type;

/**
 * Who raised it: a gate pre-block (the run waits, no tokens burn) or the
 * model's own question (batched, never blocking the current action).
 */
export const ApprovalSource = Schema.Literal("gate", "agent").annotations({ identifier: "ApprovalSource" });
export type ApprovalSource = typeof ApprovalSource.Type;

/**
 * What kind of decision this is. Wire data (cluster keys serialize), so
 * open for extension; kernel's own matches stay exhaustive in-crate.
 */
export const ApprovalClass = Schema.Union(
  Schema.Literal("commitment", "budget_limit", "discard_escalate", "agent_question"),
  Schema.Literal("governance"),
  Schema.Literal("delegation"),
  Schema.Literal("undoable"),
).annotations({ identifier: "ApprovalClass" });
export type ApprovalClass = typeof ApprovalClass.Type;

/**
 * The clustering key: class + free detail. One human verdict on a key
 * can become a Policy — for the one class that admits policies.
 */
export const ClusterKey = Schema.Struct({
  class: ApprovalClass,
  detail: Schema.String,
}).annotations({ identifier: "ClusterKey" });
export type ClusterKey = typeof ClusterKey.Type;

/**
 * Where content is: `cas:b3-<hash>` or `file:<address>@<oid>`, each with an              optional `#L<a>-<b>` or `#B<a>-<b>` range, as `kernel::locator` parses it.
 */
export const Locator = Schema.String.pipe(Schema.brand("Locator"));
export type Locator = typeof Locator.Type;

/**
 * UTC milliseconds as an integer (determinism rule 6). Always a
 * parameter, never sampled inside kernel or memory.
 */
export const TimeMs = Schema.Int.pipe(Schema.brand("TimeMs"));
export type TimeMs = typeof TimeMs.Type;

export const ApprovalItem = Schema.Struct({
  action_desc: Schema.String,
  actor: Schema.String,
  artifact: Locator,
  cluster_key: ClusterKey,
  created: TimeMs,
  id: ApprovalId,
  source: ApprovalSource,
  tainted: Schema.Boolean,
}).annotations({ identifier: "ApprovalItem" });
export type ApprovalItem = typeof ApprovalItem.Type;

/**
 * What is waiting for a person, as the Ledger recorded it.
 * 
 * The whole item travels rather than a summary of it. An interface that
 * groups identical questions needs the cluster key, and one that leads
 * with the longest wait needs the arrival time; a summary type that
 * dropped both forced the page to render every item as its own group
 * under a sentence nobody wrote. `tainted` needs no special carriage
 * here for the same reason - it is a field of the item itself.
 */
export const ApprovalsAnswer = Schema.Struct({
  items: Schema.Array(ApprovalItem),
}).annotations({ identifier: "ApprovalsAnswer" });
export type ApprovalsAnswer = typeof ApprovalsAnswer.Type;

export const ArchiveHit = Schema.Struct({
  building: Address,
  day: Schema.Int,
  kind: Schema.String,
  subject: Schema.String,
}).annotations({ identifier: "ArchiveHit" });
export type ArchiveHit = typeof ArchiveHit.Type;

/**
 * Archive hits across every building, read from the shelves at the
 * moment of asking. The files are the authority; an index kept beside
 * them would be a second copy of what the disk says.
 */
export const ArchiveAnswer = Schema.Struct({
  hits: Schema.Array(ArchiveHit),
  needle: Schema.String,
}).annotations({ identifier: "ArchiveAnswer" });
export type ArchiveAnswer = typeof ArchiveAnswer.Type;

/**
 * One line of a building's archive index.
 */
export const ArchiveLine = Schema.Struct({
  day: Schema.Int,
  kind: Schema.String,
  subject: Schema.String,
}).annotations({ identifier: "ArchiveLine" });
export type ArchiveLine = typeof ArchiveLine.Type;

/**
 * A node's place in the plan, as the first column spells it: `2`,
 * `2.3`, `2.3.1`. The parent is the prefix, so the tree needs no second
 * field to say where a node hangs.
 * 
 * Ordering is the reading order of the table — `1`, `1.1`, `1.2`, `2` —
 * because segment-wise comparison is exactly that order.
 */
export const NodeId = Schema.String.pipe(Schema.brand("NodeId"));
export type NodeId = typeof NodeId.Type;

/**
 * One cause, and how much is waiting behind it.
 */
export const BlockedLine = Schema.Struct({
  line: Schema.String,
  source: NodeId,
  waiting: Schema.Int,
}).annotations({ identifier: "BlockedLine" });
export type BlockedLine = typeof BlockedLine.Type;

/**
 * One document of a building, as it stands on disk.
 * 
 * The text is bounded: these files are written by agents over months,
 * and a page that ships an unbounded file has no answer for the day one
 * of them reaches a hundred megabytes. When it is cut, it says so -
 * silence about a cut is the difference between a view and a lie.
 */
export const BuildingDoc = Schema.Struct({
  bytes: Schema.Int,
  name: Schema.String,
  text: Schema.String,
  truncated: Schema.Boolean,
}).annotations({ identifier: "BuildingDoc" });
export type BuildingDoc = typeof BuildingDoc.Type;

/**
 * How this city reaches one server. Exhaustive rather than a URL that
 * might also be a command: the two are different machines to start
 * talking to, they fail differently, and a configuration that leaves it
 * to be guessed is one that guesses wrong on the day it matters.
 */
export const McpTransport = Schema.Union(
  Schema.Struct({
    stdio: Schema.Struct({
      args: Schema.Array(Schema.String),
      command: Schema.String,
    }),
  }),
  Schema.Struct({
    http: Schema.Struct({
      header: Schema.optional(Schema.NullOr(Schema.String)),
      url: Schema.String,
    }),
  }),
).annotations({ identifier: "McpTransport" });
export type McpTransport = typeof McpTransport.Type;

/**
 * How one external server is named inside this city.
 * 
 * The label is the first segment of every tool that server offers
 * (`{label}_{tool}`), so two servers that both offer `search` stay two
 * tools rather than becoming one that sometimes does the wrong thing.
 * Its grammar is [`ToolName`]'s minus the underscore: allowing one
 * would let `apps_foo_bar` be read as two different splits, and this
 * name routes a call.
 * 
 * It lives here rather than beside the protocol that uses it because
 * the rule it enforces is a rule about tool names, and a rule written
 * in two crates is a rule with two authorities.
 */
export const ServerLabel = Schema.String.pipe(Schema.brand("ServerLabel"));
export type ServerLabel = typeof ServerLabel.Type;

/**
 * One external tool server this run may reach, as its configuration
 * states it: a label, a program on this machine, and that program's
 * arguments.
 * 
 * The command and its arguments are host facts, for the same reason
 * the sandbox keeps them out: a city carried to another machine must
 * not carry this machine's paths inside its history. They live in
 * `CONFIG.toml` and never in a ledger payload.
 */
export const McpServer = Schema.Struct({
  label: ServerLabel,
  transport: McpTransport,
}).annotations({ identifier: "McpServer" });
export type McpServer = typeof McpServer.Type;

/**
 * The five states, closed. The spellings below are the canonical table
 * strings, and there is exactly one set of them: a second set would be a
 * second authority over what a resident is allowed to write.
 * 
 * The serde spellings are `snake_case` identifiers rather than the table
 * words: a wire frame is read by a program and a table cell by a person,
 * and making the client carry `Awaiting approval` would put an English
 * sentence where the phrase table belongs.
 */
export const RoadmapStatus = Schema.Literal("not_started", "in_progress", "done", "blocked", "awaiting_approval").annotations({ identifier: "RoadmapStatus" });
export type RoadmapStatus = typeof RoadmapStatus.Type;

/**
 * One node of a building's plan, flattened for a renderer.
 * 
 * The tree travels as rows in reading order rather than as nested
 * objects: every face the client draws — the list, the board, a branch
 * summary — wants a different grouping, and a shape that favoured one
 * of them would make the others re-flatten it.
 */
export const PlanRow = Schema.Struct({
  evidence: Schema.optional(Schema.NullOr(Schema.String)),
  item: Schema.String,
  leaf: Schema.Boolean,
  needs: Schema.Array(NodeId),
  node: NodeId,
  ready: Schema.Boolean,
  share_ppb: Schema.Int,
  status: RoadmapStatus,
}).annotations({ identifier: "PlanRow" });
export type PlanRow = typeof PlanRow.Type;

/**
 * Progress with a denominator: the leaves of the plan tree.
 * 
 * Unlike [`Completion`], progress carries serde: it is a reading of a
 * file that the interface renders, not a claim that work finished. What
 * must not be deserialisable is a `Done` — and that still is not.
 * 
 * **Two figures, because either alone misleads.** The share says how
 * much of the plan is behind you and moves when a branch is divided
 * generously; the leaf count says how many pieces the plan turned out
 * to have and does not. A reader seeing `83% / 4 leaves left` can tell
 * the difference between work finished and work redistributed, and a
 * reader seeing one number cannot.
 */
export const PlannedProgress = Schema.Struct({
  blocked: Schema.Int,
  blocked_ppb: Schema.Int,
  done: Schema.Int,
  done_ppb: Schema.Int,
  total: Schema.Int,
}).annotations({ identifier: "PlannedProgress" });
export type PlannedProgress = typeof PlannedProgress.Type;

/**
 * Whole tokens.
 */
export const Tokens = Schema.Int.pipe(Schema.brand("Tokens"));
export type Tokens = typeof Tokens.Type;

/**
 * One micro-USD. Decimal price lists convert at the single accounting
 * entry point (S3 gateway::cost); decisions never touch floats.
 */
export const UsdMicros = Schema.Int.pipe(Schema.brand("UsdMicros"));
export type UsdMicros = typeof UsdMicros.Type;

export const BudgetUse = Schema.Struct({
  tokens: Tokens,
  usd: UsdMicros,
}).annotations({ identifier: "BudgetUse" });
export type BudgetUse = typeof BudgetUse.Type;

/**
 * Progress without a denominator: steps walked and budget burned. No
 * ratio method exists — the interface cannot paint what it cannot know
 * (A17's type half).
 */
export const UnplannedProgress = Schema.Struct({
  budget: BudgetUse,
  steps: Schema.Int,
}).annotations({ identifier: "UnplannedProgress" });
export type UnplannedProgress = typeof UnplannedProgress.Type;

/**
 * Deliberately exhaustive: both faces must be handled by every renderer.
 */
export const Progress = Schema.Union(
  Schema.Struct({
    planned: PlannedProgress,
  }),
  Schema.Struct({
    unplanned: UnplannedProgress,
  }),
).annotations({ identifier: "Progress" });
export type Progress = typeof Progress.Type;

/**
 * One environment variable name a scope declares its runs may inherit.
 * 
 * A `String` would put the judgement in whichever caller remembered it.
 * This has one constructor, and that constructor is reached where a
 * configuration file is read — which is the only moment the refusal is
 * still worth anything, because a name handed to a child process is a
 * name the child cannot be asked to forget.
 */
export const EnvVarName = Schema.String.pipe(Schema.brand("EnvVarName"));
export type EnvVarName = typeof EnvVarName.Type;

/**
 * What a run's execution boundary allows. Resolved as one value rather
 * than field by field: a layer that speaks about the sandbox speaks
 * about all of it, so an under-specified layer can only ever reduce
 * what a run may do, never silently grant something the layer above it
 * never mentioned.
 * 
 * Host facts are deliberately absent — where the Python artifact lives
 * and which shell binary exists belong to the machine, not to the city,
 * and a city carried to another machine must not carry its paths.
 */
export const SandboxLimits = Schema.Struct({
  env_passthrough: Schema.optional(Schema.Array(EnvVarName)),
  fuel: Schema.Int,
  mounts: Schema.Array(Address),
  shell: Schema.Boolean,
}).annotations({ identifier: "SandboxLimits" });
export type SandboxLimits = typeof SandboxLimits.Type;

/**
 * What one building is: its plan, its own documents, its rooms and what
 * it has filed. The answer a person reads when they ask "what happened
 * in there".
 */
export const BuildingAnswer = Schema.Struct({
  addr: Address,
  archive: Schema.Array(ArchiveLine),
  blocked: Schema.Array(BlockedLine),
  docs: Schema.Array(BuildingDoc),
  mcp: Schema.Array(McpServer),
  plan: Schema.Array(PlanRow),
  problems: Schema.Array(Schema.String),
  progress: Progress,
  rooms: Schema.Array(Schema.String),
  sandbox: Schema.optional(Schema.NullOr(SandboxLimits)),
}).annotations({ identifier: "BuildingAnswer" });
export type BuildingAnswer = typeof BuildingAnswer.Type;

/**
 * What happened to the file.
 * 
 * `Renamed` is its own arm because a rename and a delete-plus-add are
 * different facts about the same two trees, and somebody deciding
 * whether an agent moved code or rewrote it needs the difference.
 */
export const How = Schema.Union(
  Schema.Literal("added", "modified", "deleted"),
  Schema.Struct({
    renamed: Schema.Struct({
      from: Schema.String,
    }),
  }),
).annotations({ identifier: "How" });
export type How = typeof How.Type;

/**
 * How much of a file moved.
 * 
 * An enum rather than two numbers, because a binary file has no line
 * count. Rendering one as `+0 −0` would be the interface reporting a
 * measurement nobody made, and a reader would take it for a file that
 * was touched and left alone.
 */
export const Lines = Schema.Union(
  Schema.Literal("binary"),
  Schema.Struct({
    counted: Schema.Struct({
      added: Schema.Int,
      removed: Schema.Int,
    }),
  }),
).annotations({ identifier: "Lines" });
export type Lines = typeof Lines.Type;

/**
 * One file, as the difference between two trees describes it.
 */
export const FileChange = Schema.Struct({
  how: How,
  lines: Lines,
  path: Schema.String,
}).annotations({ identifier: "FileChange" });
export type FileChange = typeof FileChange.Type;

/**
 * A git object id: exactly 40 lowercase hex digits.
 */
export const GitOid = Schema.String.pipe(Schema.brand("GitOid"));
export type GitOid = typeof GitOid.Type;

/**
 * What moved between two checkpoints, one row per file, path order.
 * 
 * Path order rather than size order: somebody looking for one file finds
 * it in the same place every time, and a list that reorders itself as
 * the numbers change cannot be scanned twice.
 */
export const ChangesAnswer = Schema.Struct({
  base: GitOid,
  files: Schema.Array(FileChange),
  head: Schema.optional(Schema.NullOr(GitOid)),
}).annotations({ identifier: "ChangesAnswer" });
export type ChangesAnswer = typeof ChangesAnswer.Type;

/**
 * A building's plan, as its own `Roadmap.md` states it.
 * 
 * `problems` carries the rows the table could not state — a row with a
 * status outside the five words, a column count that is not six, or a
 * dependency that runs in a circle. The interface shows them: a plan
 * that quietly drops the lines it could not parse would report progress
 * against a denominator nobody chose.
 */
export const BuildingProgress = Schema.Struct({
  addr: Address,
  blocked: Schema.Array(BlockedLine),
  problems: Schema.Array(Schema.String),
  progress: Progress,
  ready: Schema.Int,
}).annotations({ identifier: "BuildingProgress" });
export type BuildingProgress = typeof BuildingProgress.Type;

/**
 * Whether a pursuit is taking work right now.
 * 
 * Carries serde because a page renders it. The value that must not be
 * deserialisable is [`Pursuit`] itself — and that still is not.
 */
export const PursuitState = Schema.Literal("running", "paused").annotations({ identifier: "PursuitState" });
export type PursuitState = typeof PursuitState.Type;

/**
 * A city's standing goal, if it has one.
 * 
 * `verdict` is the city's own reading of whether there is anything left
 * to do, so a page never has to work out the stop condition for itself
 * — which is what would give the condition a second authority.
 */
export const PursuitLine = Schema.Struct({
  addr: Address,
  goal: Schema.String,
  state: PursuitState,
  verdict: Schema.String,
}).annotations({ identifier: "PursuitLine" });
export type PursuitLine = typeof PursuitLine.Type;

/**
 * The closed event vocabulary.
 */
export const EventKind = Schema.Union(
  Schema.Literal("city_initialized", "building_created", "run_started", "run_forked", "prompt_assembled", "model_called", "model_returned", "tool_called", "tool_result", "result_offloaded", "gate_checked", "gate_denied", "checkpoint_committed", "handoff_written", "steer_received", "cancel_received", "watchdog_fired", "budget_limit", "run_frozen", "log_truncated", "signal_enqueued", "signal_consumed", "draft_held", "draft_resolved", "goal_registered", "goal_conflict", "arbitration_verdict", "repair_started", "repair_reused", "worktree_opened", "pr_opened", "pr_merged", "pr_rejected", "roadmap_claimed", "roadmap_finished", "roadmap_released", "approval_requested", "approval_resolved", "policy_created", "policy_revoked", "taint_promoted", "cross_building_transfer", "takeover_started", "rollback_applied", "city_halted", "backpressure_shed", "digest_invalidated", "endpoint_attached", "endpoint_lost", "model_selected", "provider_degraded", "login_started", "eval_run", "asset_archived", "credential_lent", "secret_captured", "secret_egress_blocked", "file_discarded", "discard_restored", "autonomy_changed"),
  Schema.Literal("building_configured"),
  Schema.Literal("roadmap_split"),
  Schema.Literal("roadmap_blocked"),
  Schema.Literal("pursuit_changed"),
  Schema.Literal("endpoint_probed"),
  Schema.Literal("governed_document_written"),
).annotations({ identifier: "EventKind" });
export type EventKind = typeof EventKind.Type;

/**
 * Run identity; uuid v7 for humans, nil for the city itself. No
 * generation here — the assembly layer (or a seeded simulator) mints.
 */
export const RunId = Schema.String.pipe(Schema.brand("RunId"));
export type RunId = typeof RunId.Type;

/**
 * Event sequence number; contiguous from [`Seq::FIRST`], checked arithmetic.
 */
export const Seq = Schema.Int.pipe(Schema.brand("Seq"));
export type Seq = typeof Seq.Type;

/**
 * One run, as a reader needs it. The client folds the live stream for
 * itself; this shape is what a query answers about runs it never saw,
 * which is why it carries the position rather than the whole history.
 */
export const RunSummary = Schema.Struct({
  addr: Schema.optional(Schema.NullOr(Address)),
  frozen: Schema.Boolean,
  last_kind: EventKind,
  last_seq: Seq,
  run: RunId,
  started: Schema.optional(Schema.NullOr(TimeMs)),
  who: Schema.String,
}).annotations({ identifier: "RunSummary" });
export type RunSummary = typeof RunSummary.Type;

export const CityAnswer = Schema.Struct({
  active: Schema.Int,
  buildings: Schema.Array(BuildingProgress),
  frozen: Schema.Int,
  halted: Schema.Array(Schema.String),
  pursuits: Schema.Array(PursuitLine),
  runs: Schema.Array(RunSummary),
}).annotations({ identifier: "CityAnswer" });
export type CityAnswer = typeof CityAnswer.Type;

/**
 * How hard the provider should think before answering, ordered from
 * least to most. Both dialects accept every level; they disagree only
 * on where `None` is written (an effort value on one wire, a separate
 * thinking field on the other).
 * 
 * The ladder mirrors the providers' own vocabularies; check theirs
 * before changing it:
 * <https://platform.claude.com/docs/en/build-with-claude/effort> and
 * <https://developers.openai.com/api/docs/guides/reasoning>.
 * 
 * Absence (`Option::None`) is not `Effort::None`: absence leaves the
 * choice to the provider, `Effort::None` asks it not to think.
 */
export const Effort = Schema.Literal("none", "low", "medium", "high", "xhigh", "max").annotations({ identifier: "Effort" });
export type Effort = typeof Effort.Type;

/**
 * What a person calls one session: one address segment, and therefore
 * one directory under a building.
 * 
 * A `String` here would put the segment rules in whichever caller
 * remembered them. This has one constructor, so a name that cannot be
 * a room cannot be spelled, on the wire or anywhere else.
 */
export const SessionName = Schema.String.pipe(Schema.brand("SessionName"));
export type SessionName = typeof SessionName.Type;

/**
 * Which run wrote one commit, in the words the commit's own git
 * trailers use.
 * 
 * Four of the five trailers appear here; `Sprawling-City` does not,
 * because whoever asked this question already holds the city. `seq` is
 * what the trailers cannot carry: where in the one history the line
 * announcing this commit sits, so a reader can go on from there.
 */
export const CommitAnswer = Schema.Struct({
  actor: Address,
  at: TimeMs,
  effort: Schema.optional(Schema.NullOr(Effort)),
  lineage: Schema.Array(RunId),
  model: Schema.String,
  oid: GitOid,
  run: RunId,
  seq: Seq,
  session: Schema.optional(Schema.NullOr(SessionName)),
}).annotations({ identifier: "CommitAnswer" });
export type CommitAnswer = typeof CommitAnswer.Type;

/**
 * One page of the commits a city made, newest first.
 * 
 * `building` and `before` are the question handed back: the wire
 * carries no request id, so a page matches an answer to what it asked
 * by content, the way `ChangesAnswer` carries `base` and `head`. `more`
 * rather than a cursor: the next page begins before the last `seq`
 * here, which the reader already holds.
 */
export const CommitsAnswer = Schema.Struct({
  before: Schema.optional(Schema.NullOr(Seq)),
  building: Schema.optional(Schema.NullOr(Address)),
  commits: Schema.Array(CommitAnswer),
  more: Schema.Boolean,
}).annotations({ identifier: "CommitsAnswer" });
export type CommitsAnswer = typeof CommitsAnswer.Type;

/**
 * The five cuts of one authoritative total. Each dimension sums to
 * `total` exactly; the interface renders shares against `total` rather
 * than normalising its own rows, so an unattributed remainder stays
 * visible instead of being divided away.
 */
export const CostAnswer = Schema.Struct({
  by_actor: Schema.Array(Schema.Tuple(Schema.String, UsdMicros)),
  by_run: Schema.Array(Schema.Tuple(Schema.String, UsdMicros)),
  by_segment: Schema.Array(Schema.Tuple(Schema.String, UsdMicros)),
  by_skill: Schema.Array(Schema.Tuple(Schema.String, UsdMicros)),
  by_tool: Schema.Array(Schema.Tuple(Schema.String, UsdMicros)),
  total: UsdMicros,
}).annotations({ identifier: "CostAnswer" });
export type CostAnswer = typeof CostAnswer.Type;

/**
 * What one plan node cost, and which runs spent it.
 */
export const CostOfAnswer = Schema.Struct({
  node: NodeId,
  runs: Schema.Array(Schema.Tuple(RunId, UsdMicros)),
  spent: UsdMicros,
}).annotations({ identifier: "CostOfAnswer" });
export type CostOfAnswer = typeof CostOfAnswer.Type;

/**
 * Tracked rides git (`file:`), Interred rides CAS (`cas:`), Rebuildable
 * names its reason. No fourth storage authority exists.
 */
export const Restoration = Schema.Union(
  Schema.Struct({
    tracked: Locator,
  }),
  Schema.Struct({
    interred: Locator,
  }),
  Schema.Struct({
    rebuildable: Schema.Struct({
      reason: Schema.String,
    }),
  }),
).annotations({ identifier: "Restoration" });
export type Restoration = typeof Restoration.Type;

export const DiscardLine = Schema.Struct({
  at: TimeMs,
  path: Schema.String,
  restoration: Schema.optional(Schema.NullOr(Restoration)),
  restored: Schema.Boolean,
}).annotations({ identifier: "DiscardLine" });
export type DiscardLine = typeof DiscardLine.Type;

/**
 * The Recycle Bin: what was discarded and how each row gets back.
 * 
 * A row without a way back cannot be constructed upstream, so every
 * row here states one; `restored` says whether somebody already took
 * it.
 */
export const DiscardAnswer = Schema.Struct({
  rows: Schema.Array(DiscardLine),
}).annotations({ identifier: "DiscardAnswer" });
export type DiscardAnswer = typeof DiscardAnswer.Type;

/**
 * What getting the item would cost on this machine.
 */
export const DoctorInstall = Schema.Union(
  Schema.Struct({
    command: Schema.Struct({
      spelled: Schema.String,
    }),
  }),
  Schema.Struct({
    print: Schema.Struct({
      spelled: Schema.String,
    }),
  }),
  Schema.Struct({
    manual: Schema.Struct({
      how: Schema.String,
    }),
  }),
  Schema.Literal("unknown_platform"),
).annotations({ identifier: "DoctorInstall" });
export type DoctorInstall = typeof DoctorInstall.Type;

/**
 * Whether a tier can be reached without the item.
 */
export const DoctorNeed = Schema.Union(
  Schema.Literal("required"),
  Schema.Literal("optional"),
).annotations({ identifier: "DoctorNeed" });
export type DoctorNeed = typeof DoctorNeed.Type;

/**
 * Which kind of not being here.
 */
export const DoctorAbsence = Schema.Union(
  Schema.Literal("not_on_search_path", "no_home", "not_in_this_build"),
  Schema.Struct({
    variable_names_nothing: Schema.Struct({
      path: Schema.String,
      variable: Schema.String,
    }),
  }),
  Schema.Struct({
    no_component: Schema.Struct({
      dir: Schema.String,
    }),
  }),
).annotations({ identifier: "DoctorAbsence" });
export type DoctorAbsence = typeof DoctorAbsence.Type;

/**
 * Why a thing that is here cannot be used.
 */
export const DoctorFault = Schema.Union(
  Schema.Struct({
    will_not_start: Schema.Struct({
      said: Schema.String,
    }),
  }),
  Schema.Literal("half_written"),
  Schema.Struct({
    unreadable: Schema.Struct({
      said: Schema.String,
    }),
  }),
).annotations({ identifier: "DoctorFault" });
export type DoctorFault = typeof DoctorFault.Type;

/**
 * What a present program said when asked its version. Only the first
 * arm carries text; the other three are facts about how it did not
 * answer, and none of them makes the program absent.
 */
export const DoctorVersion = Schema.Union(
  Schema.Struct({
    said: Schema.Struct({
      text: Schema.String,
    }),
  }),
  Schema.Literal("silent"),
  Schema.Literal("unreadable"),
  Schema.Literal("late"),
).annotations({ identifier: "DoctorVersion" });
export type DoctorVersion = typeof DoctorVersion.Type;

/**
 * Whether the item is here, and in what condition.
 */
export const DoctorState = Schema.Union(
  Schema.Struct({
    present: Schema.Struct({
      at: Schema.String,
      version: DoctorVersion,
    }),
  }),
  Schema.Struct({
    broken: Schema.Struct({
      at: Schema.String,
      fault: DoctorFault,
    }),
  }),
  Schema.Struct({
    absent: Schema.Struct({
      absence: DoctorAbsence,
    }),
  }),
).annotations({ identifier: "DoctorState" });
export type DoctorState = typeof DoctorState.Type;

/**
 * Who needs an item, and therefore which verdict it counts towards.
 */
export const DoctorTier = Schema.Union(
  Schema.Literal("use"),
  Schema.Literal("develop"),
).annotations({ identifier: "DoctorTier" });
export type DoctorTier = typeof DoctorTier.Type;

/**
 * One item, and this machine's answer about it.
 */
export const DoctorItem = Schema.Struct({
  enables: Schema.String,
  install: DoctorInstall,
  name: Schema.String,
  need: DoctorNeed,
  state: DoctorState,
  tier: DoctorTier,
}).annotations({ identifier: "DoctorItem" });
export type DoctorItem = typeof DoctorItem.Type;

/**
 * Whether one tier is reachable on this machine.
 */
export const DoctorVerdict = Schema.Struct({
  missing: Schema.Array(Schema.String),
  tier: DoctorTier,
}).annotations({ identifier: "DoctorVerdict" });
export type DoctorVerdict = typeof DoctorVerdict.Type;

/**
 * This machine, item by item, with a verdict for each tier.
 */
export const DoctorAnswer = Schema.Struct({
  items: Schema.Array(DoctorItem),
  tiers: Schema.Array(DoctorVerdict),
}).annotations({ identifier: "DoctorAnswer" });
export type DoctorAnswer = typeof DoctorAnswer.Type;

/**
 * One file's head, and what was left out.
 */
export const DocumentAnswer = Schema.Struct({
  at: Address,
  binary: Schema.Boolean,
  bytes: Schema.Int,
  text: Schema.String,
  truncated: Schema.Boolean,
}).annotations({ identifier: "DocumentAnswer" });
export type DocumentAnswer = typeof DocumentAnswer.Type;

/**
 * What a chosen model is for. Exhaustive rather than a free label: a
 * tag exists because some code asks for a model by it, so a tag with no
 * asker is a setting the person can fill in and never see used. It
 * grows when a caller appears, not when a name is imagined.
 */
export const ModelTag = Schema.Union(
  Schema.Literal("main"),
  Schema.Literal("digest"),
).annotations({ identifier: "ModelTag" });
export type ModelTag = typeof ModelTag.Type;

export const ChosenSummary = Schema.Struct({
  endpoint: Schema.String,
  max_output_tokens: Schema.Int,
  model: Schema.String,
  tag: ModelTag,
}).annotations({ identifier: "ChosenSummary" });
export type ChosenSummary = typeof ChosenSummary.Type;

/**
 * Which wire the far side speaks. Open for growth; every match on it
 * handles the known kinds exhaustively and fails closed.
 * 
 * Lives here rather than in `gateway` for the same reason
 * [`BuildingPolicy`] does: two outer crates must name it (the gateway
 * translates it, the wire carries it) and neither may name the other.
 * `gateway::dialect` is its evaluator, not its definition.
 */
export const DialectKind = Schema.Literal("anthropic", "open_ai").annotations({ identifier: "DialectKind" });
export type DialectKind = typeof DialectKind.Type;

/**
 * One attached endpoint, as a reader may see it. No credential appears
 * here in any form; `has_credential` answers the only question a page
 * needs, which is whether one was enrolled at all.
 */
export const EndpointSummary = Schema.Struct({
  base_url: Schema.String,
  dialect: DialectKind,
  has_credential: Schema.Boolean,
  local: Schema.Boolean,
  models: Schema.Array(Schema.String),
  name: Schema.String,
}).annotations({ identifier: "EndpointSummary" });
export type EndpointSummary = typeof EndpointSummary.Type;

/**
 * What the settings page reads back: what is attached, and what each
 * tag currently points at.
 */
export const EndpointsAnswer = Schema.Struct({
  chosen: Schema.Array(ChosenSummary),
  endpoints: Schema.Array(EndpointSummary),
}).annotations({ identifier: "EndpointsAnswer" });
export type EndpointsAnswer = typeof EndpointsAnswer.Type;

/**
 * Which kind of evidence one row is.
 * 
 * Exhaustive and small: a row exists because the Ledger holds a
 * locator, and there are two records that write one.
 */
export const EvidenceKind = Schema.Union(
  Schema.Literal("screenshot"),
  Schema.Literal("finished"),
).annotations({ identifier: "EvidenceKind" });
export type EvidenceKind = typeof EvidenceKind.Type;

/**
 * The two sides and the media type of a picture, as the record wrote
 * them. Absent on a row whose record named a locator and no size,
 * which is a row worth showing and not a size worth inventing.
 */
export const Picture = Schema.Struct({
  height: Schema.Int,
  media_type: Schema.String,
  width: Schema.Int,
}).annotations({ identifier: "Picture" });
export type Picture = typeof Picture.Type;

/**
 * One thing a run wrote down that can be looked at again.
 */
export const EvidenceItem = Schema.Struct({
  at: Seq,
  kind: EvidenceKind,
  locator: Locator,
  picture: Schema.optional(Schema.NullOr(Picture)),
}).annotations({ identifier: "EvidenceItem" });
export type EvidenceItem = typeof EvidenceItem.Type;

/**
 * Everything one run left as evidence, oldest first.
 */
export const EvidenceAnswer = Schema.Struct({
  items: Schema.Array(EvidenceItem),
  run: RunId,
}).annotations({ identifier: "EvidenceAnswer" });
export type EvidenceAnswer = typeof EvidenceAnswer.Type;

/**
 * Non-empty resident identity; the `role@building.n` grammar tightens
 * with city::resident (P1).
 */
export const ResidentId = Schema.String.pipe(Schema.brand("ResidentId"));
export type ResidentId = typeof ResidentId.Type;

/**
 * Who answers the Approval Inbox (9.2). Never touches gate decisions —
 * C15's byte-identical gate sequences are citysim's to assert (P2).
 */
export const Autonomy = Schema.Union(
  Schema.Literal("owner", "deferred"),
  Schema.Struct({
    delegate: ResidentId,
  }),
).annotations({ identifier: "Autonomy" });
export type Autonomy = typeof Autonomy.Type;

export const PolicyVerdict = Schema.Literal("allow", "deny").annotations({ identifier: "PolicyVerdict" });
export type PolicyVerdict = typeof PolicyVerdict.Type;

/**
 * One approval, as it was answered.
 */
export const Decision = Schema.Struct({
  at: TimeMs,
  cluster: ClusterKey,
  item: Schema.String,
  verdict: PolicyVerdict,
}).annotations({ identifier: "Decision" });
export type Decision = typeof Decision.Type;

/**
 * Who answers for this city, and what was answered on the person's
 * behalf.
 * 
 * One shape for both halves: a list of decisions with nobody named
 * beside it does not say whether the person delegated them, and a
 * delegation with nothing under it does not say whether it was ever
 * used.
 */
export const GovernanceAnswer = Schema.Struct({
  autonomy: Autonomy,
  decided: Schema.Array(Decision),
}).annotations({ identifier: "GovernanceAnswer" });
export type GovernanceAnswer = typeof GovernanceAnswer.Type;

/**
 * A BLAKE3 digest: exactly 64 lowercase hex digits.
 */
export const B3Hash = Schema.String.pipe(Schema.brand("B3Hash"));
export type B3Hash = typeof B3Hash.Type;

/**
 * Ledger payload: a JSON object with every float refused, at construction
 * and again on read (determinism rule 6). Keys serialize sorted
 * (serde_json's default BTreeMap), which is part of the canonical bytes.
 */
export const Payload = Schema.Record({ key: Schema.String, value: Schema.Unknown }).annotations({ identifier: "Payload" });
export type Payload = typeof Payload.Type;

/**
 * One serialized history line. Fields private: the only paths to a
 * record are [`EventRecord::from_draft`] (append side) and
 * [`EventRecord::parse_line`] (read side).
 */
export const EventRecord = Schema.Struct({
  addr: Schema.optional(Schema.NullOr(Address)),
  data: Payload,
  ig: Schema.optional(Schema.Boolean),
  kind: EventKind,
  prev: B3Hash,
  run: RunId,
  seq: Seq,
  t: TimeMs,
  v: Schema.Int,
  who: Schema.String,
}).annotations({ identifier: "EventRecord" });
export type EventRecord = typeof EventRecord.Type;

/**
 * A slice of the one history, oldest first.
 * 
 * Oldest first because that is the order the ledger wrote them and the
 * order a fold expects; a reader that wants the newest first reverses a
 * list it already has, and a server that reversed it would make the
 * fold the caller's problem.
 */
export const HistoryAnswer = Schema.Struct({
  earlier: Schema.optional(Schema.NullOr(Seq)),
  records: Schema.Array(EventRecord),
}).annotations({ identifier: "HistoryAnswer" });
export type HistoryAnswer = typeof HistoryAnswer.Type;

/**
 * One line of patch text, numbered from the top of the patch so a
 * withheld line and the lines around it read as one list.
 */
export const PatchLine = Schema.Struct({
  number: Schema.Int,
  text: Schema.String,
}).annotations({ identifier: "PatchLine" });
export type PatchLine = typeof PatchLine.Type;

/**
 * One line that was not echoed, and what matched it.
 */
export const Withheld = Schema.Struct({
  number: Schema.Int,
  reason: Schema.String,
}).annotations({ identifier: "Withheld" });
export type Withheld = typeof Withheld.Type;

/**
 * One file's patch text between two checkpoints, and what could not be
 * shown.
 * 
 * Both ends travel back with the answer because they are what makes it
 * cacheable: two commit ids never change, so whoever asked may keep
 * this for as long as they like.
 */
export const HunksAnswer = Schema.Struct({
  lines: Schema.Array(PatchLine),
  oid_a: GitOid,
  oid_b: GitOid,
  path: Schema.String,
  withheld: Schema.Array(Withheld),
}).annotations({ identifier: "HunksAnswer" });
export type HunksAnswer = typeof HunksAnswer.Type;

export const SignalLine = Schema.Struct({
  at: TimeMs,
  from: Schema.String,
  id: Schema.String,
  kind: Schema.String,
}).annotations({ identifier: "SignalLine" });
export type SignalLine = typeof SignalLine.Type;

/**
 * What waits in one room, without taking it.
 * 
 * Folded from the ledger rather than read off the queue: a queue that
 * is read by being consumed cannot also be looked at, and a view that
 * consumed what it showed would be a view that changes the thing it
 * reports on.
 */
export const InboxAnswer = Schema.Struct({
  addr: Address,
  waiting: Schema.Array(SignalLine),
}).annotations({ identifier: "InboxAnswer" });
export type InboxAnswer = typeof InboxAnswer.Type;

/**
 * What one entry is. A directory has no size worth stating: the size
 * of a directory is a question about everything under it, and this
 * answer deliberately does not walk that far.
 */
export const EntryKind = Schema.Union(
  Schema.Literal("directory"),
  Schema.Struct({
    file: Schema.Struct({
      bytes: Schema.Int,
    }),
  }),
).annotations({ identifier: "EntryKind" });
export type EntryKind = typeof EntryKind.Type;

/**
 * One name inside a directory.
 */
export const Entry = Schema.Struct({
  kind: EntryKind,
  name: Schema.String,
}).annotations({ identifier: "Entry" });
export type Entry = typeof Entry.Type;

/**
 * One directory, one level deep: directories first, then files, each
 * group in name order, so a tree drawn from it reads the same way on
 * every machine.
 */
export const ListingAnswer = Schema.Struct({
  at: Schema.optional(Schema.NullOr(Address)),
  entries: Schema.Array(Entry),
}).annotations({ identifier: "ListingAnswer" });
export type ListingAnswer = typeof ListingAnswer.Type;

/**
 * The city's vital signs: the counts a page would otherwise assemble
 * by asking four questions and adding up the answers.
 * 
 * Every number here is already proven by another view; this query
 * exists so that drawing one readout costs one question. It holds no
 * money - that is `CostView`'s, and one figure with two owners is how
 * two figures start disagreeing.
 */
export const MetricsAnswer = Schema.Struct({
  approvals_waiting: Schema.Int,
  buildings: Schema.Int,
  discards_outstanding: Schema.Int,
  events: Schema.Int,
  runs_active: Schema.Int,
  runs_frozen: Schema.Int,
  signals_waiting: Schema.Int,
}).annotations({ identifier: "MetricsAnswer" });
export type MetricsAnswer = typeof MetricsAnswer.Type;

export const RegistryLine = Schema.Struct({
  addr: Address,
  at: TimeMs,
  kind: Schema.String,
  subject: Schema.String,
}).annotations({ identifier: "RegistryLine" });
export type RegistryLine = typeof RegistryLine.Type;

/**
 * What this city has decided is worth keeping.
 */
export const RegistryAnswer = Schema.Struct({
  assets: Schema.Array(RegistryLine),
}).annotations({ identifier: "RegistryAnswer" });
export type RegistryAnswer = typeof RegistryAnswer.Type;

/**
 * How a session ended, in the word the run froze with: `done`,
 * `limit` or `cancelled`.
 */
export const Closing = Schema.Struct({
  at: TimeMs,
  completion: Schema.String,
}).annotations({ identifier: "Closing" });
export type Closing = typeof Closing.Type;

/**
 * How a session began: what the person asked for, in their words.
 * 
 * The rounds start at the first `model_called`, so without this the
 * first thing said in a conversation - the task - is the one thing the
 * answer never carried.
 */
export const Opening = Schema.Struct({
  at: TimeMs,
  goal: Schema.String,
  task: Schema.String,
}).annotations({ identifier: "Opening" });
export type Opening = typeof Opening.Type;

/**
 * What a tool call has come to so far.
 * 
 * Three states rather than a `bool` and an `Option`: a call still
 * running and a call that failed are different things to a person
 * deciding whether to step in, and the pair could spell a fourth state
 * that cannot happen.
 */
export const Outcome = Schema.Union(
  Schema.Literal("waiting"),
  Schema.Literal("answered"),
  Schema.Literal("failed"),
).annotations({ identifier: "Outcome" });
export type Outcome = typeof Outcome.Type;

/**
 * What a tool said, bounded so a wave of output cannot become the page.
 * 
 * The cut is counted rather than hinted at: a reader who cannot see how
 * much was withheld is being dumped on slowly. Bytes already too large
 * were replaced by `runtime::offload` before they reached the Ledger,
 * and that substitute carries its own line naming the `Locator`.
 */
export const Output = Schema.Struct({
  cut: Schema.Int,
  head: Schema.String,
}).annotations({ identifier: "Output" });
export type Output = typeof Output.Type;

/**
 * One tool call inside a turn.
 */
export const Call = Schema.Struct({
  at: Seq,
  outcome: Outcome,
  output: Schema.optional(Schema.NullOr(Output)),
  subject: Schema.optional(Schema.NullOr(Schema.String)),
  tool: Schema.String,
}).annotations({ identifier: "Call" });
export type Call = typeof Call.Type;

/**
 * One of the closed set of error codes, as `AxCode::as_str` spells it.
 */
export const AxCode = Schema.Literal("E_PATH_NOT_FOUND", "E_TOOL_UNKNOWN", "E_TOOL_UNAVAILABLE", "E_INVALID_ARGS", "E_OUTSIDE_WRITE_DOMAIN", "E_VERSION_CONFLICT", "E_GATE_DENIED", "E_BUDGET_EXHAUSTED", "E_TIMEOUT", "E_PROVIDER", "E_EVIDENCE_MISSING", "E_LOOP_SUSPECTED", "E_LOCATOR_INVALID", "E_SANDBOX_DENIED", "E_DRAFT_STALE", "E_GOAL_CONFLICT", "E_TAINTED_ACTION", "E_REPAIR_BUSY", "E_DELEGATION_DEPTH", "E_APPROVAL_PENDING", "E_APPROVAL_DENIED", "E_CROSS_BUILDING_DENIED", "E_DIGEST_SUSPECT", "E_CREDENTIAL_MISSING", "E_CONFIG_INVALID", "E_CAS_CORRUPT", "E_STORAGE_FATAL", "E_WORKTREE_BUSY", "E_BROWSER_UNAVAILABLE", "E_ENDPOINT_DIALECT_UNSUPPORTED", "E_WIRE_MISMATCH", "E_LOG_VERSION_UNSUPPORTED", "E_SECRET_EGRESS", "E_DISCARD_IRREVERSIBLE", "E_BACKPRESSURE_SHED", "E_TOOL_OUTCOME_UNKNOWN").annotations({ identifier: "AxCode" });
export type AxCode = typeof AxCode.Type;

/**
 * The three mandatory parts of a gate refusal: rule | violation |
 * compliant alternative (three-part refusal).
 */
export const GateRefusal = Schema.Struct({
  alternative: Schema.String,
  rule: Schema.String,
  violation: Schema.String,
}).annotations({ identifier: "GateRefusal" });
export type GateRefusal = typeof GateRefusal.Type;

/**
 * The unified error shape: seven wire fields, serialized in declaration
 * order (determinism rule 6). The model is the recovery subject: `nearby`
 * and `recovery` must hold directly executable information, not apologies.
 * 
 * Everything but `code` sits behind one Box so the type stays cheap in
 * every seam's return slot (`result_large_err`); serde flatten keeps the
 * wire shape flat and the field order unchanged.
 */
export const AxError = Schema.Struct({
  action: Schema.String,
  code: AxCode,
  gate: Schema.optional(Schema.NullOr(GateRefusal)),
  nearby: Schema.Array(Schema.String),
  recovery: Schema.String,
  retriable: Schema.Boolean,
  subject: Schema.String,
}).annotations({ identifier: "AxError" });
export type AxError = typeof AxError.Type;

/**
 * What a turn came to besides the calls it made.
 * 
 * **The criterion is closed on purpose**: an event earns a `Note` when
 * it changed what this turn did, or what it is waiting on. Everything
 * else stays in the event stream, which is the Ledger's shape rather
 * than a reader's. Without that line this enum would grow to one arm
 * per event kind and stop meaning anything.
 */
export const Note = Schema.Union(
  Schema.Struct({
    refused: Schema.Struct({
      at: Seq,
      error: AxError,
    }),
  }),
  Schema.Struct({
    fenced: Schema.Struct({
      at: Seq,
      oid: GitOid,
    }),
  }),
  Schema.Struct({
    waiting: Schema.Struct({
      at: Seq,
    }),
  }),
  Schema.Struct({
    arrived: Schema.Struct({
      at: Seq,
      from: Schema.String,
      said: Schema.String,
    }),
  }),
  Schema.Struct({
    discarded: Schema.Struct({
      at: Seq,
      count: Schema.Int,
    }),
  }),
).annotations({ identifier: "Note" });
export type Note = typeof Note.Type;

/**
 * What one turn cost in tokens.
 * 
 * Absolute counts and no ratio: the numerator is on the wire and the
 * denominator - this model's context window - is not. A percentage with
 * no denominator is the thing `UnplannedProgress` already refuses to
 * spell, and it would be no more honest here.
 */
export const Used = Schema.Struct({
  cached: Tokens,
  input: Tokens,
  output: Tokens,
}).annotations({ identifier: "Used" });
export type Used = typeof Used.Type;

/**
 * One turn: the model was asked, and this is what came of it.
 */
export const Turn = Schema.Struct({
  calls: Schema.Array(Call),
  notes: Schema.Array(Note),
  number: Schema.Int,
  opened: Seq,
  said: Schema.optional(Schema.NullOr(Schema.String)),
  spent: Schema.optional(Schema.NullOr(UsdMicros)),
  stopped: Schema.optional(Schema.NullOr(Schema.String)),
  used: Schema.optional(Schema.NullOr(Used)),
}).annotations({ identifier: "Turn" });
export type Turn = typeof Turn.Type;

/**
 * One session's rounds, oldest first.
 */
export const RoundsAnswer = Schema.Struct({
  closing: Schema.optional(Schema.NullOr(Closing)),
  opened_at: Schema.optional(Schema.NullOr(GitOid)),
  opening: Schema.optional(Schema.NullOr(Opening)),
  run: RunId,
  turns: Schema.Array(Turn),
}).annotations({ identifier: "RoundsAnswer" });
export type RoundsAnswer = typeof RoundsAnswer.Type;

/**
 * What a query returns. `Unavailable` is a real answer: a view this
 * build does not evaluate yet says so by name, rather than returning an
 * empty result a reader would mistake for an empty city.
 * 
 * `Eq` went when `History` arrived: a record's payload is arbitrary
 * JSON, and JSON has no total equality. Nothing compared two answers
 * for equality outside a test.
 */
export const Answer = Schema.Union(
  Schema.Struct({
    history: HistoryAnswer,
  }),
  Schema.Struct({
    changes: ChangesAnswer,
  }),
  Schema.Struct({
    commit: CommitAnswer,
  }),
  Schema.Struct({
    city: CityAnswer,
  }),
  Schema.Struct({
    run: Schema.NullOr(RunSummary),
  }),
  Schema.Struct({
    approvals: ApprovalsAnswer,
  }),
  Schema.Struct({
    cost: CostAnswer,
  }),
  Schema.Struct({
    endpoints: EndpointsAnswer,
  }),
  Schema.Struct({
    building: BuildingAnswer,
  }),
  Schema.Struct({
    inbox: InboxAnswer,
  }),
  Schema.Struct({
    discards: DiscardAnswer,
  }),
  Schema.Struct({
    registry: RegistryAnswer,
  }),
  Schema.Struct({
    archive: ArchiveAnswer,
  }),
  Schema.Struct({
    metrics: MetricsAnswer,
  }),
  Schema.Struct({
    governance: GovernanceAnswer,
  }),
  Schema.Struct({
    hunks: HunksAnswer,
  }),
  Schema.Struct({
    rounds: RoundsAnswer,
  }),
  Schema.Struct({
    evidence: EvidenceAnswer,
  }),
  Schema.Struct({
    cost_of: CostOfAnswer,
  }),
  Schema.Struct({
    listing: ListingAnswer,
  }),
  Schema.Struct({
    document: DocumentAnswer,
  }),
  Schema.Struct({
    commits: CommitsAnswer,
  }),
  Schema.Struct({
    doctor: DoctorAnswer,
  }),
  Schema.Struct({
    unavailable: Schema.Struct({
      query: Schema.String,
    }),
  }),
).annotations({ identifier: "Answer" });
export type Answer = typeof Answer.Type;

/**
 * Which of the three documents that govern a city a `PutDocument`
 * frame carries.
 * 
 * A closed set rather than a path, because where these files live is
 * the city's answer and not the sender's: all three sit in the city's
 * own reserved subtree, which no write domain reaches. A frame naming
 * its own path would be a way to write anywhere inside the one place a
 * resident may not edit.
 */
export const GovernedDocument = Schema.Union(
  Schema.Literal("mayor"),
  Schema.Literal("clerk"),
  Schema.Literal("preferences"),
).annotations({ identifier: "GovernedDocument" });
export type GovernedDocument = typeof GovernedDocument.Type;

/**
 * What a Halt, Release or Autonomy change applies to. Unlike modes and
 * providers, this set is the protocol's own and has no upstream owner.
 */
export const HaltScope = Schema.Union(
  Schema.Literal("city"),
  Schema.Struct({
    building: Address,
  }),
  Schema.Struct({
    workshop: Address,
  }),
).annotations({ identifier: "HaltScope" });
export type HaltScope = typeof HaltScope.Type;

/**
 * The deduplication key of one outward action: `idem1-` then 32 lowercase hex digits.
 */
export const IdemKey = Schema.String.pipe(Schema.brand("IdemKey"));
export type IdemKey = typeof IdemKey.Type;

/**
 * Which step of a subscription login a `Login` frame carries.
 * 
 * The authorization code arrives by hand: the provider shows it to the
 * person after they approve, and the person brings it back. That is
 * the flow the profile table describes, and it needs no listening port
 * of its own.
 */
export const LoginStep = Schema.Union(
  Schema.Literal("begin"),
  Schema.Struct({
    code: Schema.Struct({
      code: Schema.String,
    }),
  }),
).annotations({ identifier: "LoginStep" });
export type LoginStep = typeof LoginStep.Type;

/**
 * A mode name in transit. Authority for the mode set is `runtime::Mode`.
 */
export const ModeTag = Schema.String.pipe(Schema.brand("ModeTag"));
export type ModeTag = typeof ModeTag.Type;

export const NoSecret = Schema.Never.annotations({ identifier: "NoSecret" });
export type NoSecret = typeof NoSecret.Type;

/**
 * A provider name in transit. Authority for the provider set is `gateway`.
 */
export const ProviderName = Schema.String.pipe(Schema.brand("ProviderName"));
export type ProviderName = typeof ProviderName.Type;

/**
 * What a `Pursue` command does to a pursuit.
 * 
 * `Clear` and `Pause` are different actions and both exist: pausing
 * keeps the goal so it can be taken up again, and clearing throws it
 * away. Cancelling a *run* is a third thing again, and it has its own
 * command.
 */
export const PursuitStep = Schema.Union(
  Schema.Literal("pause", "resume", "clear"),
  Schema.Struct({
    set: Schema.Struct({
      goal: Schema.String,
    }),
  }),
).annotations({ identifier: "PursuitStep" });
export type PursuitStep = typeof PursuitStep.Type;

/**
 * A Building template name in transit. Authority is `city`.
 */
export const TemplateName = Schema.String.pipe(Schema.brand("TemplateName"));
export type TemplateName = typeof TemplateName.Type;

/**
 * Handle for bytes already delivered to the upload endpoint.
 */
export const UploadId = Schema.String.pipe(Schema.brand("UploadId"));
export type UploadId = typeof UploadId.Type;

/**
 * Commands change state, require authorization, and are idempotent.
 * 
 * Deliberately *not* `#[non_exhaustive]`: the schema hash is this type's
 * version mechanism, so the assembly layer must handle every one of them
 * and a new one fails to compile until somebody decides what it does.
 * That is the rule that keeps a button off the client until the city can
 * answer the frame behind it.
 */
export const Command = Schema.Union(
  Schema.Struct({
    dispatch: Schema.Struct({
      addr: Address,
      effort: Schema.optional(Schema.NullOr(Effort)),
      goal: Schema.String,
      idem: IdemKey,
      mode: ModeTag,
      session: Schema.optional(Schema.NullOr(SessionName)),
      task: Schema.String,
    }),
  }),
  Schema.Struct({
    login: Schema.Struct({
      idem: IdemKey,
      provider: ProviderName,
      step: LoginStep,
    }),
  }),
  Schema.Struct({
    probe_endpoint: Schema.Struct({
      auth_header: Schema.optional(Schema.NullOr(Schema.String)),
      base_url: Schema.String,
      dialect: DialectKind,
      idem: IdemKey,
      name: ProviderName,
      secret: Schema.optional(Schema.NullOr(Schema.String)),
    }),
  }),
  Schema.Struct({
    configure_building: Schema.Struct({
      addr: Address,
      desktop: Schema.optional(Schema.NullOr(Schema.String)),
      idem: IdemKey,
      mcp: Schema.optional(Schema.NullOr(Schema.Array(McpServer))),
      sandbox: Schema.optional(Schema.NullOr(SandboxLimits)),
    }),
  }),
  Schema.Struct({
    attach_endpoint: Schema.Struct({
      admit: Schema.Array(Schema.String),
      auth_header: Schema.optional(Schema.NullOr(Schema.String)),
      base_url: Schema.String,
      dialect: DialectKind,
      idem: IdemKey,
      name: ProviderName,
      secret: Schema.optional(Schema.NullOr(Schema.String)),
    }),
  }),
  Schema.Struct({
    select_model: Schema.Struct({
      context_tokens: Schema.Int,
      endpoint: ProviderName,
      idem: IdemKey,
      max_output_tokens: Schema.Int,
      model: Schema.String,
      tag: ModelTag,
    }),
  }),
  Schema.Struct({
    fork: Schema.Struct({
      addr: Schema.optional(Schema.NullOr(Address)),
      at_seq: Seq,
      idem: IdemKey,
      run: RunId,
    }),
  }),
  Schema.Struct({
    attach: Schema.Struct({
      idem: IdemKey,
      notify: Schema.Array(RunId),
      upload: UploadId,
    }),
  }),
  Schema.Struct({
    create_building: Schema.Struct({
      addr: Address,
      idem: IdemKey,
      template: TemplateName,
    }),
  }),
  Schema.Struct({
    put_secret: Schema.Struct({
      name: Schema.String,
      realm: Schema.String,
      value: NoSecret,
    }),
  }),
  Schema.Struct({
    steer: Schema.Struct({
      idem: IdemKey,
      run: RunId,
      text: Schema.String,
    }),
  }),
  Schema.Struct({
    cancel: Schema.Struct({
      idem: IdemKey,
      run: RunId,
    }),
  }),
  Schema.Struct({
    takeover: Schema.Struct({
      idem: IdemKey,
      run: RunId,
    }),
  }),
  Schema.Struct({
    rollback: Schema.Struct({
      checkpoint: GitOid,
      idem: IdemKey,
    }),
  }),
  Schema.Struct({
    halt: Schema.Struct({
      idem: IdemKey,
      scope: HaltScope,
    }),
  }),
  Schema.Struct({
    release: Schema.Struct({
      idem: IdemKey,
      scope: HaltScope,
    }),
  }),
  Schema.Struct({
    batch_by_building: Schema.Struct({
      addr: Address,
      idem: IdemKey,
    }),
  }),
  Schema.Struct({
    approve: Schema.Struct({
      idem: IdemKey,
      item: ApprovalId,
      verdict: PolicyVerdict,
    }),
  }),
  Schema.Struct({
    create_policy: Schema.Struct({
      from_item: ApprovalId,
      idem: IdemKey,
    }),
  }),
  Schema.Struct({
    set_autonomy: Schema.Struct({
      autonomy: Autonomy,
      idem: IdemKey,
      scope: HaltScope,
    }),
  }),
  Schema.Struct({
    pursue: Schema.Struct({
      addr: Address,
      idem: IdemKey,
      step: PursuitStep,
    }),
  }),
  Schema.Struct({
    wake: Schema.Struct({
      body: Schema.String,
      idem: IdemKey,
      source: Schema.String,
      subject: Schema.String,
    }),
  }),
  Schema.Struct({
    put_document: Schema.Struct({
      body: Schema.String,
      idem: IdemKey,
      which: GovernedDocument,
    }),
  }),
  Schema.Struct({
    auth: Schema.Struct({
      token: Schema.String,
    }),
  }),
).annotations({ identifier: "Command" });
export type Command = typeof Command.Type;

/**
 * The client's opening frame.
 */
export const Hello = Schema.Struct({
  schema: B3Hash,
  token: Schema.optional(Schema.NullOr(Schema.String)),
  wire_v: Schema.Int,
}).annotations({ identifier: "Hello" });
export type Hello = typeof Hello.Type;

/**
 * Queries read state. They are cacheable and free of side effects, so none
 * carries an `IdemKey` - a Query that needed one would have stopped being a
 * Query.
 */
export const Query = Schema.Union(
  Schema.Literal("city_view", "approval_queue", "metrics", "cost_view", "registry_view", "discard_view"),
  Schema.Struct({
    history: Schema.Struct({
      before: Schema.optional(Schema.NullOr(Seq)),
      limit: Schema.Int,
    }),
  }),
  Schema.Struct({
    run_history: Schema.Struct({
      before: Schema.optional(Schema.NullOr(Seq)),
      limit: Schema.Int,
      run: RunId,
    }),
  }),
  Schema.Struct({
    changes: Schema.Struct({
      base: GitOid,
      head: Schema.optional(Schema.NullOr(GitOid)),
    }),
  }),
  Schema.Struct({
    hunks: Schema.Struct({
      oid_a: GitOid,
      oid_b: GitOid,
      path: Schema.String,
    }),
  }),
  Schema.Struct({
    commit: Schema.Struct({
      oid: GitOid,
    }),
  }),
  Schema.Struct({
    run_view: Schema.Struct({
      run: RunId,
    }),
  }),
  Schema.Struct({
    inbox_view: Schema.Struct({
      addr: Address,
    }),
  }),
  Schema.Struct({
    archive_search: Schema.Struct({
      needle: Schema.String,
    }),
  }),
  Schema.Literal("endpoint_view"),
  Schema.Struct({
    building_view: Schema.Struct({
      addr: Address,
    }),
  }),
  Schema.Literal("governance"),
  Schema.Struct({
    rounds: Schema.Struct({
      run: RunId,
    }),
  }),
  Schema.Struct({
    evidence: Schema.Struct({
      run: RunId,
    }),
  }),
  Schema.Struct({
    cost_of: Schema.Struct({
      node: NodeId,
    }),
  }),
  Schema.Struct({
    listing: Schema.Struct({
      at: Schema.optional(Schema.NullOr(Address)),
    }),
  }),
  Schema.Struct({
    document: Schema.Struct({
      at: Address,
    }),
  }),
  Schema.Struct({
    commits: Schema.Struct({
      before: Schema.optional(Schema.NullOr(Seq)),
      building: Schema.optional(Schema.NullOr(Address)),
      limit: Schema.Int,
    }),
  }),
  Schema.Literal("doctor"),
).annotations({ identifier: "Query" });
export type Query = typeof Query.Type;

/**
 * Everything a client may send.
 */
export const ClientFrame = Schema.Union(
  Schema.Struct({
    hello: Hello,
  }),
  Schema.Struct({
    command: Command,
  }),
  Schema.Struct({
    query: Query,
  }),
).annotations({ identifier: "ClientFrame" });
export type ClientFrame = typeof ClientFrame.Type;

/**
 * One piece of what a model is saying, on its way to a page.
 */
export const Delta = Schema.Struct({
  run: RunId,
  text: Schema.String,
}).annotations({ identifier: "Delta" });
export type Delta = typeof Delta.Type;

/**
 * The server's answer to a `Hello` it accepted.
 */
export const Welcome = Schema.Struct({
  city: Schema.optional(Schema.NullOr(Address)),
  resume_from: Schema.optional(Schema.NullOr(Seq)),
  schema: B3Hash,
  wire_v: Schema.Int,
}).annotations({ identifier: "Welcome" });
export type Welcome = typeof Welcome.Type;

/**
 * Everything a server may send. Events are the push half; a `Refusal`
 * carries the three-part refusal the interface renders verbatim.
 * 
 * **`Delta` is deliberately not an event.** An event is a thing that
 * happened, and a token increment is not: it has no sequence number, it
 * is never written to the Ledger, it cannot be replayed, and a client
 * that missed one has lost nothing. Giving it a frame class of its own
 * is what keeps that true — folded into the event stream it would
 * become a second, unverifiable history of what the model said.
 */
export const ServerFrame = Schema.Union(
  Schema.Struct({
    welcome: Welcome,
  }),
  Schema.Struct({
    event: EventRecord,
  }),
  Schema.Struct({
    answer: Answer,
  }),
  Schema.Struct({
    refusal: AxError,
  }),
  Schema.Struct({
    delta: Delta,
  }),
).annotations({ identifier: "ServerFrame" });
export type ServerFrame = typeof ServerFrame.Type;

