// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

//! One JSON Schema document in, one `wire.ts` out.
//!
//! The emitter reads the subset serde produces for this wire and nothing
//! more: objects, the five primitive types, arrays and tuples, string
//! enums and constants, `oneOf`/`anyOf`, `$ref` into `$defs`, a type
//! list that adds `null`, and the two boolean schemas. Any other keyword
//! is refused with its place, because a generator that guesses is a
//! generator that emits a wrong type without saying so.
//!
//! Definitions come out in dependency order with names as the tie-break:
//! an Effect `Schema` is a runtime value, so what a struct refers to must
//! already be defined when the struct is.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::{Map, Value};

/// Where the emitter stopped, and on what.
#[derive(Debug)]
pub(super) struct Refused {
    pub(super) at: String,
    pub(super) why: String,
}

/// Every keyword the emitter reads; one it does not know is a refusal.
const KNOWN: &str = concat!(
    "$ref additionalProperties anyOf const default description enum format items ",
    "maxItems minItems minimum oneOf pattern prefixItems properties required type",
);

const REF_PREFIX: &str = "#/$defs/";

pub(super) fn emit(document: &Value, wire_v: u32, hash: &str) -> Result<String, Refused> {
    let defs: BTreeMap<&str, &Value> = document
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| refuse("$defs", "the document has no `$defs` object"))?
        .iter()
        .map(|(name, schema)| (name.as_str(), schema))
        .collect();
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "export const WIRE_V = {wire_v} as const;");
    out.push_str("/** The schema hash the server checks: `channels::schema_hash()`. */\n");
    let _ = writeln!(out, "export const WIRE_HASH = \"{hash}\" as const;\n");
    for name in ordered(&defs)? {
        let schema = defs
            .get(name.as_str())
            .ok_or_else(|| refuse(&name, "named by a `$ref` and absent from `$defs`"))?;
        out.push_str(&definition(&name, schema)?);
    }
    Ok(out)
}

const HEADER: &str = "// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
//
// Generated by `cargo xtask wire-ts` from `crates/channels` (channels-SPEC.md
// section 8-16). Do not edit: change the Rust wire types and regenerate.

import { Schema } from \"effect\";

/** The wire version both ends compare on connect. */
";

fn refuse(at: &str, why: impl Into<String>) -> Refused {
    Refused {
        at: at.to_owned(),
        why: why.into(),
    }
}

/// Every definition, each after the ones it refers to. Depth-first from
/// the names in order, so ties fall alphabetically and the output is the
/// same on every machine.
fn ordered(defs: &BTreeMap<&str, &Value>) -> Result<Vec<String>, Refused> {
    let mut done = Vec::new();
    let mut trail = Vec::new();
    for name in defs.keys() {
        visit(name, defs, &mut trail, &mut done)?;
    }
    Ok(done)
}

fn visit(
    name: &str,
    defs: &BTreeMap<&str, &Value>,
    trail: &mut Vec<String>,
    done: &mut Vec<String>,
) -> Result<(), Refused> {
    if done.iter().any(|d| d == name) {
        return Ok(());
    }
    if trail.iter().any(|t| t == name) {
        let cycle = trail.join(" -> ");
        return Err(refuse(
            name,
            format!(
                "`{name}` refers to itself through {cycle}; a recursive type is outside the subset"
            ),
        ));
    }
    let schema = defs
        .get(name)
        .ok_or_else(|| refuse(name, "named by a `$ref` and absent from `$defs`"))?;
    trail.push(name.to_owned());
    let mut refs = BTreeSet::new();
    refs_within(schema, &mut refs);
    for target in refs {
        visit(&target, defs, trail, done)?;
    }
    trail.pop();
    done.push(name.to_owned());
    Ok(())
}

fn refs_within(schema: &Value, out: &mut BTreeSet<String>) {
    match schema {
        Value::Object(map) => {
            if let Some(name) = map
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|target| target.strip_prefix(REF_PREFIX))
            {
                out.insert(name.to_owned());
            }
            map.values().for_each(|v| refs_within(v, out));
        }
        Value::Array(items) => items.iter().for_each(|v| refs_within(v, out)),
        _ => {}
    }
}

/// One `export const` and its `export type`, with the description as a
/// doc comment. A named bare primitive is a newtype and gets its brand;
/// every other definition carries its name as the identifier a decode
/// error prints.
fn definition(name: &str, schema: &Value) -> Result<String, Refused> {
    if !is_identifier(name) {
        return Err(refuse(name, "not a TypeScript identifier"));
    }
    let mut out = String::new();
    if let Some(description) = schema.get("description").and_then(Value::as_str) {
        out.push_str("/**\n");
        for line in description.lines() {
            let _ = writeln!(out, " * {}", line.replace("*/", "*\\/"));
        }
        out.push_str(" */\n");
    }
    let body = expression(schema, name, 0)?;
    // A brand already prints as `string & Brand<"Name">` in a decode
    // error; everything else is named so the error says `Command`
    // rather than spelling the whole union out.
    let body = if is_bare_primitive(schema) {
        format!("{body}.pipe(Schema.brand(\"{name}\"))")
    } else {
        format!("{body}.annotations({{ identifier: \"{name}\" }})")
    };
    let _ = writeln!(out, "export const {name} = {body};");
    let _ = writeln!(out, "export type {name} = typeof {name}.Type;\n");
    Ok(out)
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn is_bare_primitive(schema: &Value) -> bool {
    let Some(map) = schema.as_object() else {
        return false;
    };
    matches!(
        map.get("type").and_then(Value::as_str),
        Some("string" | "integer" | "number" | "boolean")
    ) && !map.contains_key("enum")
        && !map.contains_key("const")
}

/// The Effect expression for one schema. `at` is where it sits, for the
/// refusal; `indent` is how deep its own lines start.
fn expression(schema: &Value, at: &str, indent: usize) -> Result<String, Refused> {
    let map = match schema {
        Value::Bool(true) => return Ok("Schema.Unknown".to_owned()),
        Value::Bool(false) => return Ok("Schema.Never".to_owned()),
        Value::Object(map) => map,
        _ => return Err(refuse(at, "a schema is an object or a boolean")),
    };
    if let Some(unknown) = map.keys().find(|k| {
        !KNOWN
            .split_ascii_whitespace()
            .any(|known| known == k.as_str())
    }) {
        return Err(refuse(
            at,
            format!("keyword `{unknown}` is outside the subset serde produces for this wire"),
        ));
    }
    if let Some(target) = map.get("$ref") {
        return reference(target, at);
    }
    if let Some(members) = map.get("oneOf").or_else(|| map.get("anyOf")) {
        return union(members, at, indent);
    }
    if let Some(values) = map.get("enum") {
        return literals(values, at);
    }
    if let Some(value) = map.get("const") {
        return literals(&Value::Array(vec![value.clone()]), at);
    }
    match map.get("type") {
        Some(kind) => typed(map, kind, at, indent),
        None => Err(refuse(
            at,
            "a schema with no `type`, `$ref`, `enum`, `const` or union",
        )),
    }
}

fn reference(target: &Value, at: &str) -> Result<String, Refused> {
    let name = target
        .as_str()
        .and_then(|t| t.strip_prefix(REF_PREFIX))
        .filter(|name| is_identifier(name))
        .ok_or_else(|| refuse(at, format!("`$ref` {target} does not point into `$defs`")))?;
    Ok(name.to_owned())
}

fn union(members: &Value, at: &str, indent: usize) -> Result<String, Refused> {
    let members = members
        .as_array()
        .ok_or_else(|| refuse(at, "`oneOf`/`anyOf` is not a list"))?;
    // `Option<T>` on a `$ref` arrives as `anyOf: [T, null]`; it is one
    // nullable value, not a union a reader has to take apart.
    if let [one, two] = members.as_slice() {
        let null = serde_json::json!({ "type": "null" });
        if two == &null {
            return Ok(format!("Schema.NullOr({})", expression(one, at, indent)?));
        }
        if one == &null {
            return Ok(format!("Schema.NullOr({})", expression(two, at, indent)?));
        }
    }
    let mut out = String::from("Schema.Union(\n");
    for (index, member) in members.iter().enumerate() {
        let member = expression(
            member,
            &format!("{at}/oneOf[{index}]"),
            indent.saturating_add(1),
        )?;
        let _ = writeln!(out, "{}{member},", pad(indent.saturating_add(1)));
    }
    let _ = write!(out, "{})", pad(indent));
    Ok(out)
}

fn literals(values: &Value, at: &str) -> Result<String, Refused> {
    let values = values
        .as_array()
        .ok_or_else(|| refuse(at, "`enum` is not a list"))?;
    let mut spelled = Vec::new();
    for value in values {
        let text = value
            .as_str()
            .ok_or_else(|| refuse(at, format!("literal {value} is not a string")))?;
        spelled.push(serde_json::to_string(text).map_err(|e| refuse(at, e.to_string()))?);
    }
    Ok(format!("Schema.Literal({})", spelled.join(", ")))
}

fn typed(
    map: &Map<String, Value>,
    kind: &Value,
    at: &str,
    indent: usize,
) -> Result<String, Refused> {
    let (kind, nullable) = match kind {
        Value::String(kind) => (kind.as_str(), false),
        Value::Array(kinds) => {
            let kinds: Vec<&str> = kinds.iter().filter_map(Value::as_str).collect();
            let rest: Vec<&str> = kinds.iter().copied().filter(|k| *k != "null").collect();
            match rest.as_slice() {
                [one] => (*one, kinds.len() > rest.len()),
                _ => {
                    return Err(refuse(
                        at,
                        format!("type list {kinds:?} names more than one type"),
                    ));
                }
            }
        }
        _ => return Err(refuse(at, "`type` is neither a string nor a list")),
    };
    let inner = match kind {
        "string" => "Schema.String".to_owned(),
        "integer" => "Schema.Int".to_owned(),
        "number" => "Schema.Number".to_owned(),
        "boolean" => "Schema.Boolean".to_owned(),
        "null" => "Schema.Null".to_owned(),
        "array" => array(map, at, indent)?,
        "object" => object(map, at, indent)?,
        other => return Err(refuse(at, format!("type `{other}` is outside the subset"))),
    };
    Ok(if nullable {
        format!("Schema.NullOr({inner})")
    } else {
        inner
    })
}

fn array(map: &Map<String, Value>, at: &str, indent: usize) -> Result<String, Refused> {
    if let Some(elements) = map.get("prefixItems").and_then(Value::as_array) {
        let mut spelled = Vec::new();
        for (index, element) in elements.iter().enumerate() {
            spelled.push(expression(
                element,
                &format!("{at}/prefixItems[{index}]"),
                indent,
            )?);
        }
        return Ok(format!("Schema.Tuple({})", spelled.join(", ")));
    }
    let item = match map.get("items") {
        Some(items) => expression(items, &format!("{at}/items"), indent)?,
        None => "Schema.Unknown".to_owned(),
    };
    Ok(format!("Schema.Array({item})"))
}

fn object(map: &Map<String, Value>, at: &str, indent: usize) -> Result<String, Refused> {
    if let Some(properties) = map.get("properties").and_then(Value::as_object) {
        return fields(properties, map.get("required"), at, indent);
    }
    match map.get("additionalProperties") {
        Some(Value::Bool(false)) => Ok("Schema.Struct({})".to_owned()),
        Some(values) => {
            let value = expression(values, &format!("{at}/additionalProperties"), indent)?;
            Ok(format!(
                "Schema.Record({{ key: Schema.String, value: {value} }})"
            ))
        }
        None => Ok("Schema.Record({ key: Schema.String, value: Schema.Unknown })".to_owned()),
    }
}

fn fields(
    properties: &Map<String, Value>,
    required: Option<&Value>,
    at: &str,
    indent: usize,
) -> Result<String, Refused> {
    let required: BTreeSet<&str> = required
        .and_then(Value::as_array)
        .map(|list| list.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let sorted: BTreeMap<&str, &Value> = properties.iter().map(|(k, v)| (k.as_str(), v)).collect();
    let mut out = String::from("Schema.Struct({\n");
    for (key, schema) in sorted {
        let value = expression(
            schema,
            &format!("{at}/properties/{key}"),
            indent.saturating_add(1),
        )?;
        let value = if required.contains(key) {
            value
        } else {
            format!("Schema.optional({value})")
        };
        let key = if is_identifier(key) {
            key.to_owned()
        } else {
            serde_json::to_string(key).map_err(|e| refuse(at, e.to_string()))?
        };
        let _ = writeln!(out, "{}{key}: {value},", pad(indent.saturating_add(1)));
    }
    let _ = write!(out, "{}}})", pad(indent));
    Ok(out)
}

fn pad(indent: usize) -> String {
    "  ".repeat(indent)
}
