// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

//! One JSON Schema document in, one `wire.ts` out.
//!
//! The emitter reads the subset serde produces for this wire and nothing
//! more: objects, the five primitive types, arrays and tuples, string
//! enums and constants, `oneOf`/`anyOf`, `$ref` into `$defs`, a type
//! list that adds `null`, and the two boolean schemas. Any other keyword
//! is refused with its place, because a generator that guesses is a
//! generator that emits a wrong type without saying so.
//!
//! Definitions come out in dependency order with names as the tie-break:
//! an Effect `Schema` is a runtime value, so what a struct refers to must
//! already be defined when the struct is.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::Value;

use super::Constants;
use values::expression;

mod values;

/// Where the emitter stopped, and on what.
#[derive(Debug)]
pub(super) struct Refused {
    pub(super) at: String,
    pub(super) why: String,
}

const REF_PREFIX: &str = "#/$defs/";

pub(super) fn emit(document: &Value, constants: &Constants) -> Result<String, Refused> {
    let defs: BTreeMap<&str, &Value> = document
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| refuse("$defs", "the document has no `$defs` object"))?
        .iter()
        .map(|(name, schema)| (name.as_str(), schema))
        .collect();
    let mut out = String::from(HEADER);
    let _ = write!(
        out,
        "export const WIRE_V = {} as const;\n\
         /** The schema hash the server checks: `channels::schema_hash()`. */\n\
         export const WIRE_HASH = \"{}\" as const;\n\
         /** The run a city-level record carries: `kernel::RunId::CITY`. */\n\
         export const CITY_RUN = \"{}\" as const;\n\n",
        constants.wire_v, constants.hash, constants.city_run
    );
    for name in ordered(&defs)? {
        let schema = defs
            .get(name.as_str())
            .ok_or_else(|| refuse(&name, "named by a `$ref` and absent from `$defs`"))?;
        out.push_str(&definition(&name, schema)?);
    }
    Ok(out)
}

const HEADER: &str = "// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
//
// Generated by `cargo xtask wire-ts` from `crates/channels` (channels-SPEC.md
// section 8-16). Do not edit: change the Rust wire types and regenerate.

import { Schema } from \"effect\";

/** The wire version both ends compare on connect. */
";

fn refuse(at: &str, why: impl Into<String>) -> Refused {
    Refused {
        at: at.to_owned(),
        why: why.into(),
    }
}

/// Every definition, each after the ones it refers to. Depth-first from
/// the names in order, so ties fall alphabetically and the output is the
/// same on every machine.
fn ordered(defs: &BTreeMap<&str, &Value>) -> Result<Vec<String>, Refused> {
    let mut done = Vec::new();
    let mut trail = Vec::new();
    for name in defs.keys() {
        visit(name, defs, &mut trail, &mut done)?;
    }
    Ok(done)
}

fn visit(
    name: &str,
    defs: &BTreeMap<&str, &Value>,
    trail: &mut Vec<String>,
    done: &mut Vec<String>,
) -> Result<(), Refused> {
    if done.iter().any(|d| d == name) {
        return Ok(());
    }
    if trail.iter().any(|t| t == name) {
        let cycle = trail.join(" -> ");
        return Err(refuse(
            name,
            format!(
                "`{name}` refers to itself through {cycle}; a recursive type is outside the subset"
            ),
        ));
    }
    let schema = defs
        .get(name)
        .ok_or_else(|| refuse(name, "named by a `$ref` and absent from `$defs`"))?;
    trail.push(name.to_owned());
    let mut refs = BTreeSet::new();
    refs_within(schema, &mut refs);
    for target in refs {
        visit(&target, defs, trail, done)?;
    }
    trail.pop();
    done.push(name.to_owned());
    Ok(())
}

fn refs_within(schema: &Value, out: &mut BTreeSet<String>) {
    match schema {
        Value::Object(map) => {
            if let Some(name) = map
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|target| target.strip_prefix(REF_PREFIX))
            {
                out.insert(name.to_owned());
            }
            map.values().for_each(|v| refs_within(v, out));
        }
        Value::Array(items) => items.iter().for_each(|v| refs_within(v, out)),
        _ => {}
    }
}

/// One `export const` and its `export type`, with the description as a
/// doc comment. A named bare primitive is a newtype and gets its brand;
/// every other definition carries its name as the identifier a decode
/// error prints.
fn definition(name: &str, schema: &Value) -> Result<String, Refused> {
    if !is_identifier(name) {
        return Err(refuse(name, "not a TypeScript identifier"));
    }
    let mut out = String::new();
    if let Some(description) = schema.get("description").and_then(Value::as_str) {
        out.push_str("/**\n");
        for line in description.lines() {
            let _ = writeln!(out, " * {}", line.replace("*/", "*\\/"));
        }
        out.push_str(" */\n");
    }
    let body = expression(schema, name, 0)?;
    // A brand already prints as `string & Brand<"Name">` in a decode
    // error; everything else is named so the error says `Command`
    // rather than spelling the whole union out.
    let body = if is_bare_primitive(schema) {
        format!("{body}.pipe(Schema.brand(\"{name}\"))")
    } else {
        format!("{body}.annotations({{ identifier: \"{name}\" }})")
    };
    let _ = writeln!(out, "export const {name} = {body};");
    let _ = writeln!(out, "export type {name} = typeof {name}.Type;\n");
    Ok(out)
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn is_bare_primitive(schema: &Value) -> bool {
    let Some(map) = schema.as_object() else {
        return false;
    };
    matches!(
        map.get("type").and_then(Value::as_str),
        Some("string" | "integer" | "number" | "boolean")
    ) && !map.contains_key("enum")
        && !map.contains_key("const")
}
