"use strict";
// Every word the page draws, in each language it speaks; <html lang> picks one.
const WORDS = {
  en: {
    playback: "Playback", sections: "Sections", chapters: "Chapters", chapter_runs: "Chapters",
    runs: "Runs", timeline: "Timeline", moments: "Key moments", commits: "Commits", messages: "Messages",
    calls: "Calls", log: "Every line", cost: "Cost", withheld: "Withheld", source: "Source", to_top: "Back to the top",
    narration: "Narration", narration_said: "written for this page; not a record of the city",
    step: "Step", axis: "Axis", speed: "Speed", first: "First", previous: "Previous", play: "Play", pause: "Pause",
    next: "Next", last: "Last", axis_order: "In order", axis_time: "In time",
    title_city: "City {city}", subtitle: "seq {from} to {through} · {span} · cutoff seq {cutoff} · {reader}",
    span: "{first} to {last}", span_none: "no line records its own time",
    reader_person: "read as the User, confidential buildings withheld",
    reader_person_all: "read as the User, confidential buildings included",
    reader_resident: "read as the resident of {addr}",
    fact_events: "lines", fact_context: "{n} outside the selection", fact_runs: "runs", fact_calls: "calls",
    fact_measured: "{n} measured", fact_commits: "commits", fact_messages: "messages", fact_cost: "billed",
    fact_unpriced: "{n} calls unpriced", fact_withheld: "withheld lines", fact_timed: "timed lines",
    fact_timed_of: "of {m}",
    empty_bundle: "This is the template: the export puts a bundle into its data block. Nothing to show yet.",
    bad_bundle: "The data block does not read as a playback bundle: {why}",
    bad_schema: "This page reads {want}; the bundle says {got}. Export it again with a matching build, or read it with a page written for that schema.",
    attention: "Needs attention", nothing_waits: "Nothing in this selection waits on anyone, and nothing was refused or failed.",
    att_approval: "an approval waits for an answer", att_pr: "a pull request is still open",
    att_unanswered: "{n} unanswered in {run}", att_flag: "show these {n} in the log",
    col_room: "Room", col_run: "Run", col_task: "Task", col_state: "State", col_outcome: "Outcome", col_policy: "Policy",
    col_lines: "Lines", col_cost: "Cost", col_seq: "Seq", col_time: "Time (UTC)", col_kind: "Kind", col_who: "Who",
    col_what: "What", col_family: "Family", col_key: "Key", col_opened: "Opened", col_closed: "Closed",
    col_members: "Lines", col_id: "Id", col_from: "From", col_to: "Room", col_sent: "Sent", col_consumed: "Taken",
    col_callee: "Called", col_called: "Asked", col_answered: "Answered", col_took: "Took",
    state_active: "active", state_frozen: "frozen", state_unknown: "state unknown",
    no_addr: "no address", city_lane: "city", task_unseen: "its task line is not in this bundle",
    unanswered: "{n} unanswered", forked: "forked from {run} at seq {seq}", child_of: "child of {run}",
    after: "after {run}", withheld_run: "a run this reader may not see", missing_run: "a run the history lacks",
    policy: "{mode} · write {write} · admit {admit} · landing {landing}", policy_none: "no policy recorded",
    outcome_frozen: "{why}", outcome_died: "its process died", outcome_running: "running at the cutoff",
    end_at: "seq {seq}", end_outside: "seq {seq}, outside the selection", end_withheld: "withheld",
    end_pending: "not yet, by the cutoff", end_missing: "missing from the history",
    tag_refused: "refused", tag_failed: "failed", tag_conflict: "conflict", tag_person: "the User",
    tag_waiting: "waiting", tag_commit: "commit",
    family_run: "run", family_approval: "approval", family_pr: "pull request",
    moment_none: "No key moment opens or closes in this selection.",
    took_measured: "{d}", took_unknown: "not measured",
    took_note: "A duration is drawn only when both of a call's moments were measured. Not measured: an older ledger, an answer the city wrote after a restart, a call not answered yet, or a withheld end.",
    model_pending_note: "A model call still pending may be an attempt a resend replaced: the next model call of the same run carries the reply.",
    callee_tool: "tool {name}", callee_model: "model {name}", name_unseen: "name not visible",
    commit_pinned: "job pinned", commit_committed: "commit", commit_merged: "merged",
    commit_job: "job {job} (a stored object; this page cannot open it offline)",
    commit_scope: "Scope", commit_files: "Files", commit_base: "Compared with", commit_trace: "Made by",
    commit_nearby: "Nearby", commit_outcome: "Pull request",
    base_previous: "this run's previous commit {oid}", base_parent: "its parent {oid}", base_none: "nothing: no earlier commit",
    trace_untraced: "the trace knows no such commit", trace_unread: "the trace failed: {code}",
    trace_elsewhere: "seq {seq}, outside the selection; widen it to read the line", trace_withheld: "a withheld call",
    trace_none: "no call is named", nearby_note: "other runs that called tools in this building: candidates, not causes",
    nearby_row: "{who}: {n} calls",
    change_patch: "+{add} −{del}", change_truncated: "{shown} lines shown, {cut} cut",
    change_empty: "no change", change_binary: "binary", change_missing: "the repository lacks an object",
    change_withheld: "withheld: a building this reader may not see",
    held_line: "line {n} held back: {why}", cut_lines: "{n} more lines did not fit the export's budget",
    merged_by: "reviewed {reviewed}, landed {commit}, verified by {by}", rejected_by: "rejected by {by}: {why}",
    pr_open: "open at the cutoff",
    messages_none: "No message was sent or taken in this selection.",
    calls_none: "No call was made in this selection.",
    commits_none: "No checkpoint in this selection.",
    filter_all: "Everything", filter_run: "Run", filter_chapter: "Chapter", filter_text: "Find", filter_context: "Lines outside the selection",
    all_runs: "every run", all_chapters: "every chapter",
    show_more: "Show {n} more", shown: "{shown} of {all}",
    unknown_seqs: "{n} lines a newer writer wrote, which this build cannot read: seq {seqs}",
    cost_total: "Billed", cost_by_run: "By run", cost_unpriced: "{calls} calls and {tokens} tokens have no price: they are not free, and are not in the total.",
    cost_cover: "Covers only what this reader sees in this selection.",
    withheld_events: "{n} lines withheld from this reader", withheld_credential: "{n} lines held back because they looked like a credential",
    withheld_buildings: "Closed buildings", withheld_kinds: "Withheld lines by kind",
    reason_confidential: "confidential", reason_rules_unreadable: "its rules could not be read",
    withheld_note: "Names and counts are shown: this page does not hide that something happened there.",
    withheld_none: "Nothing was withheld from this reader.",
    src_schema: "Schema", src_city: "City", src_selection: "Selection", src_cutoff: "Cutoff", src_rules: "Projection rules",
    src_reader: "Reader", src_check: "Check",
    src_check_line: "sprawling playback check <this file> --city <city>",
    src_note: "A consistent bundle says its parts agree; only a check against the city, or against a bundle you trust, says it was not changed. Neither proves a line's claim about the world.",
    sel_everything: "everything up to the cutoff", sel_from: "from seq {v}", sel_through: "through seq {v}",
    sel_run: "run {v}", sel_building: "within {v}", sel_since: "since {v}", sel_until: "until {v}",
    card_none: "No line in this selection.", card_seq: "seq {seq}", card_place_event: "in the selection",
    card_place_context: "outside the selection, carried to explain it",
    card_time: "Time", card_no_time: "no time recorded for this line",
    card_time_note: "Measured when it happened. Each line keeps its own precision.",
    card_unmeasured_note: "A call or an answer whose moment was not measured: a line written before this ledger measured moments. Nothing is guessed for it.",
    card_untimed_note: "Only model and tool calls and their answers record a moment of their own; this kind of line does not.",
    card_run: "Run", card_who: "Who", card_addr: "Where", card_kind: "Kind", card_call: "Call",
    card_line: "The ledger line", card_said: "Narration",
    where: "line {i} of {n} · seq {seq}", where_time: "line {i} of {n} timed · seq {seq}",
    axis_order_note: "Each mark is one line, in the order the ledger booked it; bars join a call to its answer.",
    axis_time_note: "Each mark sits at its own measured moment. {untimed} lines record none (only calls and their answers do) and stay off this axis. Gaps longer than a minute are shortened, and each says how long it was. Bars are measured call durations only.",
    axis_time_none: "No line in this selection records its own moment, so there is no time axis; read it in order.",
    gap: "+{d}", legend_line: "line", legend_flag: "refused or failed", legend_conflict: "conflict",
    legend_person: "the User", legend_commit: "commit", legend_call: "call",
    plot_label: "Swimlanes: {lanes} runs and {n} lines. Use the step controls or the arrow keys to move through them.",
    keys: "Keys: ← → step, Space plays, Home and End jump.",
    ms: "{n} ms", s: "{n} s", min: "{m} min {s} s", h: "{h} h {m} min", d: "{d} d {h} h",
  },
  zh: {
    playback: "回放", sections: "章节", chapters: "章节", chapter_runs: "分章",
    runs: "运行", timeline: "时间线", moments: "关键时刻", commits: "提交", messages: "消息",
    calls: "调用", log: "全部记录", cost: "费用", withheld: "隐去", source: "来源", to_top: "回到顶部",
    narration: "解说", narration_said: "为本页写的说明，不是城的记录",
    step: "步进", axis: "坐标", speed: "速度", first: "最前", previous: "上一条", play: "播放", pause: "暂停",
    next: "下一条", last: "最后", axis_order: "按次序", axis_time: "按时间",
    title_city: "城 {city}", subtitle: "seq {from} 至 {through} · {span} · 截止 seq {cutoff} · {reader}",
    span: "{first} 至 {last}", span_none: "没有一行记下自己的时刻",
    reader_person: "以 User 的身份读，机密楼已隐去",
    reader_person_all: "以 User 的身份读，含机密楼",
    reader_resident: "以 {addr} 的居民身份读",
    fact_events: "记录", fact_context: "范围外 {n} 条", fact_runs: "运行", fact_calls: "调用",
    fact_measured: "{n} 次量过", fact_commits: "提交", fact_messages: "消息", fact_cost: "已计费",
    fact_unpriced: "{n} 次调用无报价", fact_withheld: "隐去的行", fact_timed: "有时刻的行",
    fact_timed_of: "共 {m} 条",
    empty_bundle: "这是模板：导出时 bundle 会放进它的数据块。现在没有可显示的内容。",
    bad_bundle: "数据块读不成 playback bundle：{why}",
    bad_schema: "本页读 {want}，bundle 写的是 {got}。用匹配的版本重新导出，或用为那个 schema 写的页面来读。",
    attention: "需要留意", nothing_waits: "这段选择里没有在等答复的事，也没有被拒绝或失败的事。",
    att_approval: "一项审批在等答复", att_pr: "一个合并请求仍未关闭",
    att_unanswered: "{run} 有 {n} 处未答", att_flag: "在记录里看这 {n} 条",
    col_room: "房间", col_run: "运行", col_task: "任务", col_state: "状态", col_outcome: "结果", col_policy: "策略",
    col_lines: "记录", col_cost: "费用", col_seq: "Seq", col_time: "时间（UTC）", col_kind: "种类", col_who: "谁",
    col_what: "内容", col_family: "类别", col_key: "键", col_opened: "开始", col_closed: "结束",
    col_members: "记录", col_id: "编号", col_from: "发自", col_to: "房间", col_sent: "发出", col_consumed: "收下",
    col_callee: "调用对象", col_called: "发起", col_answered: "答复", col_took: "耗时",
    state_active: "进行中", state_frozen: "已冻结", state_unknown: "状态不明",
    no_addr: "无地址", city_lane: "城", task_unseen: "它的任务那一行不在这份 bundle 里",
    unanswered: "{n} 处未答", forked: "从 {run} 的 seq {seq} 分叉", child_of: "{run} 的子运行",
    after: "接续 {run}", withheld_run: "本读者看不到的运行", missing_run: "历史里缺的运行",
    policy: "{mode} · 写 {write} · 准入 {admit} · 落地 {landing}", policy_none: "没有记录策略",
    outcome_frozen: "{why}", outcome_died: "进程中止", outcome_running: "截止时仍在运行",
    end_at: "seq {seq}", end_outside: "seq {seq}，在范围外", end_withheld: "已隐去",
    end_pending: "截止时尚未发生", end_missing: "历史里没有",
    tag_refused: "被拒绝", tag_failed: "失败", tag_conflict: "冲突", tag_person: "User 的介入",
    tag_waiting: "等待中", tag_commit: "提交",
    family_run: "运行", family_approval: "审批", family_pr: "合并请求",
    moment_none: "这段选择里没有关键时刻开始或结束。",
    took_measured: "{d}", took_unknown: "未量",
    took_note: "只有调用的两端都量过时刻才画耗时。未量：较早的账本、城在重启后补写的答复、尚未答复、或一端被隐去。",
    model_pending_note: "仍未答复的模型调用可能是被重发取代的一次尝试：同一运行的下一次模型调用带着答复。",
    callee_tool: "工具 {name}", callee_model: "模型 {name}", name_unseen: "名字不可见",
    commit_pinned: "钉住任务", commit_committed: "提交", commit_merged: "已合并",
    commit_job: "任务 {job}（存储里的对象；本页离线时打不开）",
    commit_scope: "范围", commit_files: "文件", commit_base: "比较基准", commit_trace: "出自",
    commit_nearby: "附近", commit_outcome: "合并请求",
    base_previous: "本运行上一个提交 {oid}", base_parent: "它的父提交 {oid}", base_none: "无：没有更早的提交",
    trace_untraced: "溯源里没有这个提交", trace_unread: "溯源失败：{code}",
    trace_elsewhere: "seq {seq}，在范围外；放宽选择才能读这一行", trace_withheld: "一次被隐去的调用",
    trace_none: "没有点名任何调用", nearby_note: "同楼里其他运行的工具调用：是候选，不是原因",
    nearby_row: "{who}：{n} 次调用",
    change_patch: "+{add} −{del}", change_truncated: "显示 {shown} 行，截去 {cut} 行",
    change_empty: "无变化", change_binary: "二进制", change_missing: "仓库里缺对象",
    change_withheld: "已隐去：本读者看不到的楼",
    held_line: "第 {n} 行未显示：{why}", cut_lines: "另有 {n} 行超出导出预算",
    merged_by: "审阅 {reviewed}，落地 {commit}，验证者 {by}", rejected_by: "{by} 拒绝：{why}",
    pr_open: "截止时仍开着",
    messages_none: "这段选择里没有消息发出或收下。",
    calls_none: "这段选择里没有调用。",
    commits_none: "这段选择里没有检查点。",
    filter_all: "全部", filter_run: "运行", filter_chapter: "章节", filter_text: "查找", filter_context: "范围外的记录",
    all_runs: "所有运行", all_chapters: "所有章节",
    show_more: "再显示 {n} 条", shown: "{all} 条中的 {shown} 条",
    unknown_seqs: "{n} 条由更新的写者写下，本版本读不懂：seq {seqs}",
    cost_total: "已计费", cost_by_run: "按运行", cost_unpriced: "{calls} 次调用、{tokens} 个 token 没有报价：它们不是免费的，也不在合计里。",
    cost_cover: "只涵盖本读者在这段选择里看得到的部分。",
    withheld_events: "对本读者隐去 {n} 条", withheld_credential: "{n} 行因像凭据而未显示",
    withheld_buildings: "关闭的楼", withheld_kinds: "按种类计的隐去条数",
    reason_confidential: "机密", reason_rules_unreadable: "规则读不了",
    withheld_note: "名字与计数照常显示：本页不隐瞒那里发生过事情。",
    withheld_none: "没有对本读者隐去任何内容。",
    src_schema: "Schema", src_city: "城", src_selection: "选择", src_cutoff: "截止", src_rules: "投影规则",
    src_reader: "读者", src_check: "复核",
    src_check_line: "sprawling playback check <本文件> --city <城>",
    src_note: "自洽只说明各部分彼此一致；只有对照城或一份你信任的 bundle 复核，才能说明它没被改过。两者都不证明一行记录所说的事在现实中为真。",
    sel_everything: "截止前的全部", sel_from: "从 seq {v}", sel_through: "到 seq {v}",
    sel_run: "运行 {v}", sel_building: "{v} 之内", sel_since: "自 {v}", sel_until: "到 {v} 前",
    card_none: "这段选择里没有记录。", card_seq: "seq {seq}", card_place_event: "在选择之内",
    card_place_context: "在选择之外，为说明它而带上",
    card_time: "时间", card_no_time: "这一行没有记录时刻",
    card_time_note: "发生时量下的时刻。每一行保留自己的精度。",
    card_unmeasured_note: "这次调用或答复没有量下时刻：它写于账本开始逐行量时刻之前。本页不替它猜。",
    card_untimed_note: "只有模型与工具的调用及其答复记下自己的时刻；这一种行不记。",
    card_run: "运行", card_who: "谁", card_addr: "地点", card_kind: "种类", card_call: "调用",
    card_line: "账本原行", card_said: "解说",
    where: "第 {i}/{n} 条 · seq {seq}", where_time: "有时刻的第 {i}/{n} 条 · seq {seq}",
    axis_order_note: "每个刻度是一行，按账本记下的次序；横条连起一次调用和它的答复。",
    axis_time_note: "每个刻度在它自己量下的时刻。{untimed} 行没有时刻（只有调用与答复才有），不放在这条轴上。超过一分钟的空档被缩短，并标出原本多长。横条只画量过的调用耗时。",
    axis_time_none: "这段选择里没有一行记下自己的时刻，所以没有时间轴；请按次序读。",
    gap: "+{d}", legend_line: "记录", legend_flag: "被拒绝或失败", legend_conflict: "冲突",
    legend_person: "User 的介入", legend_commit: "提交", legend_call: "调用",
    plot_label: "泳道：{lanes} 个运行，{n} 行。用步进按钮或方向键逐条移动。",
    keys: "按键：← → 步进，空格播放，Home 与 End 跳到两端。",
    ms: "{n} 毫秒", s: "{n} 秒", min: "{m} 分 {s} 秒", h: "{h} 小时 {m} 分", d: "{d} 天 {h} 小时",
  },
};
const LANG = document.documentElement.lang.toLowerCase().startsWith("zh") ? "zh" : "en";
function say(key, fill) {
  const text = WORDS[LANG][key] ?? WORDS.en[key] ?? key;
  return fill ? text.replace(/\{(\w+)\}/g, (_, name) => String(fill[name] ?? "")) : text;
}

// The schema this page was written for.
