// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

//! One JSON Schema document in, one `wire.ts` out, written for Effect 4.
//!
//! The emitter reads the subset serde produces for this wire and nothing
//! more: objects, the five primitive types, arrays and tuples, string
//! enums and constants, `oneOf`/`anyOf`, `$ref` into `$defs`, a type
//! list that adds `null`, and the two boolean schemas. Any other keyword
//! is refused with its place, because a generator that guesses is a
//! generator that emits a wrong type without saying so.
//!
//! Definitions come out in dependency order with names as the tie-break:
//! an Effect `Schema` is a runtime value, so what a struct refers to must
//! already be defined when the struct is. A definition that reaches
//! itself through its references is the exception: its references into
//! the cycle are `Schema.suspend`, read when a value is decoded rather
//! than when the file loads, and its two types are written out, because
//! TypeScript cannot infer a type from an initialiser that refers to
//! itself.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::Value;

use super::Constants;
use types::{Side, Types, object_body};
use values::Values;

mod types;
mod values;

/// Where the emitter stopped, and on what.
#[derive(Debug)]
pub(super) struct Refused {
    pub(super) at: String,
    pub(super) why: String,
}

const REF_PREFIX: &str = "#/$defs/";

pub(super) fn emit(document: &Value, constants: &Constants) -> Result<String, Refused> {
    let defs: BTreeMap<&str, &Value> = document
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| refuse("$defs", "the document has no `$defs` object"))?
        .iter()
        .map(|(name, schema)| (name.as_str(), schema))
        .collect();
    let mut out = String::from(HEADER);
    let _ = write!(
        out,
        "export const WIRE_V = {} as const;\n\
         /** The schema hash the server checks: `wire::schema_hash()`. */\n\
         export const WIRE_HASH = \"{}\" as const;\n\
         /** The run a city-level record carries: `kernel::RunId::CITY`. */\n\
         export const CITY_RUN = \"{}\" as const;\n\
         /** The smallest body size a person may ask for: `wire::BODY_PX_MIN`. */\n\
         export const BODY_PX = {{ min: {} }} as const;\n\n",
        constants.wire_v, constants.hash, constants.city_run, constants.body_px_min
    );
    let edges = edges(&defs);
    let recursive = recursive(&edges);
    for name in ordered(&edges)? {
        let schema = defs
            .get(name.as_str())
            .ok_or_else(|| refuse(&name, "named by a `$ref` and absent from `$defs`"))?;
        out.push_str(&definition(&name, schema, &recursive)?);
    }
    Ok(out)
}

const HEADER: &str = "// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
//
// Generated by `cargo xtask wire-ts` from `crates/wire` (crates/wire/Spec.lean
// section 8-16). Do not edit: change the Rust wire types and regenerate.

import { Schema } from \"effect\";

/** The wire version both ends compare on connect. */
";

fn refuse(at: &str, why: impl Into<String>) -> Refused {
    Refused {
        at: at.to_owned(),
        why: why.into(),
    }
}

/// Every definition, each after the ones it refers to outside a cycle.
/// Depth-first from the names in order, so ties fall alphabetically and
/// the output is the same on every machine.
fn ordered(edges: &BTreeMap<String, BTreeSet<String>>) -> Result<Vec<String>, Refused> {
    let mut done = Vec::new();
    let mut trail = Vec::new();
    for name in edges.keys() {
        visit(name, edges, &mut trail, &mut done)?;
    }
    Ok(done)
}

/// A name already on the trail closes a cycle. The definitions on a
/// cycle reach each other through `Schema.suspend`, so no order is owed
/// among them.
fn visit(
    name: &str,
    edges: &BTreeMap<String, BTreeSet<String>>,
    trail: &mut Vec<String>,
    done: &mut Vec<String>,
) -> Result<(), Refused> {
    if done.iter().any(|d| d == name) || trail.iter().any(|t| t == name) {
        return Ok(());
    }
    let refs = edges
        .get(name)
        .ok_or_else(|| refuse(name, "named by a `$ref` and absent from `$defs`"))?;
    trail.push(name.to_owned());
    for target in refs {
        visit(target, edges, trail, done)?;
    }
    trail.pop();
    done.push(name.to_owned());
    Ok(())
}

/// Every definition and the definitions it refers to.
fn edges(defs: &BTreeMap<&str, &Value>) -> BTreeMap<String, BTreeSet<String>> {
    defs.iter()
        .map(|(name, schema)| {
            let mut refs = BTreeSet::new();
            refs_within(schema, &mut refs);
            ((*name).to_owned(), refs)
        })
        .collect()
}

/// The definitions that reach themselves through their references:
/// every member of a cycle, and nothing that only refers into one.
fn recursive(edges: &BTreeMap<String, BTreeSet<String>>) -> BTreeSet<String> {
    edges
        .keys()
        .filter(|name| {
            let mut seen = BTreeSet::new();
            let mut next: Vec<&String> = edges.get(*name).into_iter().flatten().collect();
            while let Some(at) = next.pop() {
                if at == *name {
                    return true;
                }
                if seen.insert(at) {
                    next.extend(edges.get(at).into_iter().flatten());
                }
            }
            false
        })
        .cloned()
        .collect()
}

fn refs_within(schema: &Value, out: &mut BTreeSet<String>) {
    match schema {
        Value::Object(map) => {
            if let Some(name) = map
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|target| target.strip_prefix(REF_PREFIX))
            {
                out.insert(name.to_owned());
            }
            map.values().for_each(|v| refs_within(v, out));
        }
        Value::Array(items) => items.iter().for_each(|v| refs_within(v, out)),
        _ => {}
    }
}

/// One `export const` and its `export type`, with the description as a
/// doc comment. A named bare primitive is a newtype and gets its brand;
/// every other definition carries its name as the identifier a decode
/// error prints. A recursive definition states its two types first and
/// annotates its value with them.
fn definition(name: &str, schema: &Value, recursive: &BTreeSet<String>) -> Result<String, Refused> {
    if !is_identifier(name) {
        return Err(refuse(name, "not a TypeScript identifier"));
    }
    let mut out = String::new();
    if let Some(description) = schema.get("description").and_then(Value::as_str) {
        out.push_str("/**\n");
        for line in description.lines() {
            let _ = writeln!(out, " * {}", line.replace("*/", "*\\/"));
        }
        out.push_str(" */\n");
    }
    let none = BTreeSet::new();
    let is_recursive = recursive.contains(name);
    let suspended = if is_recursive { recursive } else { &none };
    let body = Values { suspended }.expression(schema, name, 0)?;
    // A brand already prints as `string & Brand<"Name">` in a decode
    // error; everything else is named so the error says `Command`
    // rather than spelling the whole union out.
    let body = if is_bare_primitive(schema) {
        format!("{body}.pipe(Schema.brand(\"{name}\"))")
    } else {
        format!("{body}.annotate({{ identifier: \"{name}\" }})")
    };
    if is_recursive {
        out.push_str(&declared(name, Side::Type, schema, recursive)?);
        out.push_str(&declared(name, Side::Encoded, schema, recursive)?);
        let _ = writeln!(
            out,
            "export const {name}: Schema.Codec<{name}, {name}Encoded> = {body};\n"
        );
    } else {
        let _ = writeln!(out, "export const {name} = {body};");
        let _ = writeln!(out, "export type {name} = typeof {name}.Type;\n");
    }
    Ok(out)
}

/// One side of a recursive definition's type, as the client's lint
/// spells it: an object type is an `interface`, anything else a `type`.
fn declared(
    name: &str,
    side: Side,
    schema: &Value,
    recursive: &BTreeSet<String>,
) -> Result<String, Refused> {
    let spelled = match side {
        Side::Type => name.to_owned(),
        Side::Encoded => format!("{name}Encoded"),
    };
    let denoted = Types { recursive, side }.denoted(schema, name)?;
    Ok(match object_body(&denoted) {
        Some(fields) => format!("export interface {spelled} {{ {fields} }}\n"),
        None => format!("export type {spelled} = {denoted}\n"),
    })
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn is_bare_primitive(schema: &Value) -> bool {
    let Some(map) = schema.as_object() else {
        return false;
    };
    matches!(
        map.get("type").and_then(Value::as_str),
        Some("string" | "integer" | "number" | "boolean")
    ) && !map.contains_key("enum")
        && !map.contains_key("const")
}
