// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "test code"
)]

//! The inbox and the bin, through the production door.

use channels::ApprovalItem;

use super::bin::{BinRow, ReturnPath, bin_rows, recycle_bin};
use super::inbox::inbox;

use channels::{ApprovalId, ApprovalSource, ClusterKey, Locator, Restoration, TimeMs};

fn item(id: &str, detail: &str, created: u64, tainted: bool) -> ApprovalItem {
    ApprovalItem {
        id: ApprovalId::new(id).unwrap(),
        source: ApprovalSource::Gate,
        actor: "resident".to_owned(),
        action_desc: format!("discard files under notes ({id})"),
        artifact: Locator::parse(&format!("file:notes/a.md@{}", "5a".repeat(20))).unwrap(),
        cluster_key: ClusterKey {
            class: channels::ApprovalClass::DiscardEscalate,
            detail: detail.to_owned(),
        },
        created: TimeMs::new(created),
        tainted,
    }
}

#[test]
fn identical_questions_arrive_as_one_decision() {
    let clusters = inbox(vec![
        item("a", "notes/", 30, false),
        item("b", "notes/", 10, false),
        item("c", "notes/", 20, false),
    ]);
    assert_eq!(clusters.len(), 1);
    assert_eq!(clusters[0].count(), 3);
    assert_eq!(clusters[0].waiting_since(), Some(TimeMs::new(10)));
    let order: Vec<&str> = clusters[0]
        .members
        .iter()
        .map(|item| item.id.as_str())
        .collect();
    assert_eq!(order, ["b", "c", "a"], "oldest first inside a group");
}

#[test]
fn a_tainted_item_cannot_be_grouped_with_anything() {
    // C15: one answer must not cover a question the person never read.
    // The tainted item keys on its own id, so there is no key to share.
    let clusters = inbox(vec![
        item("a", "notes/", 10, false),
        item("b", "notes/", 11, true),
        item("c", "notes/", 12, false),
    ]);
    assert_eq!(clusters.len(), 2);
    let lone = clusters
        .iter()
        .find(|c| c.answer_individually)
        .expect("the tainted item stands alone");
    assert_eq!(lone.count(), 1);
    assert_eq!(lone.members[0].id.as_str(), "b");
}

#[test]
fn the_longest_wait_leads_the_list() {
    let clusters = inbox(vec![
        item("a", "later/", 90, false),
        item("b", "earlier/", 5, false),
    ]);
    let leading = clusters.first().expect("two groups");
    assert_eq!(leading.waiting_since(), Some(TimeMs::new(5)));
}

#[test]
fn grouping_is_stable_so_two_people_see_one_list() {
    let make = || {
        vec![
            item("a", "x/", 10, false),
            item("b", "y/", 10, false),
            item("c", "z/", 10, false),
        ]
    };
    let mut reversed = make();
    reversed.reverse();
    assert_eq!(inbox(make()), inbox(reversed));
}

#[test]
fn every_discarded_row_can_say_how_it_comes_back() {
    let paths = [
        Restoration::Tracked(
            Locator::parse(&format!("file:notes/a.md@{}", "5a".repeat(20))).unwrap(),
        ),
        Restoration::Interred(
            Locator::parse(
                "cas:b3-0000000000000000000000000000000000000000000000000000000000000000",
            )
            .unwrap(),
        ),
        Restoration::Rebuildable {
            reason: "regenerated by the build".to_owned(),
        },
    ];
    for restoration in &paths {
        let path = ReturnPath::of(restoration);
        assert_ne!(path, ReturnPath::Undescribed);
        let sentence = path.sentence(crate::lang::Lang::En);
        assert!(
            sentence.contains("restore") || sentence.contains("rebuild"),
            "a row must name an action: {sentence}"
        );
    }
}

#[test]
fn an_unknown_restoration_scheme_offers_no_button_it_cannot_honour() {
    // Fail-closed for a view: still show the row, never invent the
    // action. A client one version behind must not promise a restore
    // whose behaviour it cannot predict.
    let sentence = ReturnPath::Undescribed.sentence(crate::lang::Lang::En);
    assert!(sentence.contains("Ledger"));
    assert!(!sentence.contains("restore from"));
    assert!(!sentence.starts_with("rebuild"));
}

fn discarded(path: &str, at: u64, way: Option<Restoration>) -> channels::DiscardLine {
    channels::DiscardLine {
        path: path.to_owned(),
        restoration: way,
        at: TimeMs::new(at),
        restored: false,
    }
}

#[test]
fn a_wire_row_becomes_a_sentence_through_the_one_place_that_writes_it() {
    // The defect this pins: the server used to compose the sentence
    // itself, so the way back had two authorities and the page had
    // none. The plan now travels as a plan.
    let tracked = Restoration::Tracked(
        Locator::parse(&format!("file:notes/a.md@{}", "5a".repeat(20))).unwrap(),
    );
    let rows = bin_rows(&channels::DiscardAnswer {
        rows: vec![discarded("file:notes/a.md", 10, Some(tracked))],
    });
    assert_eq!(rows.len(), 1);
    assert!(
        rows[0]
            .return_path
            .sentence(crate::lang::Lang::En)
            .contains("checkpoint")
    );
    assert!(!rows[0].restored);
}

#[test]
fn a_plan_this_build_cannot_read_still_gets_a_row_and_no_invented_action() {
    let rows = bin_rows(&channels::DiscardAnswer {
        rows: vec![discarded("file:notes/b.md", 11, None)],
    });
    assert_eq!(rows.len(), 1, "the row is never dropped");
    assert_eq!(rows[0].return_path, ReturnPath::Undescribed);
    assert!(
        rows[0]
            .return_path
            .sentence(crate::lang::Lang::En)
            .contains("Ledger")
    );
}

#[test]
fn a_row_somebody_already_took_back_says_so_instead_of_disappearing() {
    let mut line = discarded("file:notes/c.md", 12, None);
    line.restored = true;
    let rows = bin_rows(&channels::DiscardAnswer { rows: vec![line] });
    assert!(rows[0].restored, "evidence that the way back worked");
}

#[test]
fn the_bin_shows_the_most_recent_mistake_first() {
    let row = |what: &str, at: u64| BinRow {
        what: what.to_owned(),
        discarded_at: TimeMs::new(at),
        restored: false,
        return_path: ReturnPath::Rebuild("make".to_owned()),
    };
    let ordered = recycle_bin(vec![row("old", 1), row("new", 9), row("mid", 5)]);
    let names: Vec<&str> = ordered.iter().map(|r| r.what.as_str()).collect();
    assert_eq!(names, ["new", "mid", "old"]);
}
